import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { LocalAdminConnection } from '../src/admin/local-connection';
import { Workbench } from '../src/core/workbench';
import { sessionContext } from '../src/core/session-context';
import { memberProfile } from './fixtures/member-profile';

test('assignments enforce live roles, preserve snapshots, and start a reusable prepared session', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'wb-assignments-')), shared = path.join(root, 'share'); await fs.mkdir(shared);
  const admin = new LocalAdminConnection(() => {}), clients: Workbench[] = [];
  try {
    await admin.connect({ mode: 'local', localRoot: shared, host: 'local', port: 22, username: '', fingerprint: '', root: '/srv/teamspace' }, '', '', async () => false);
    await admin.operation({ op: 'initialize' }); await admin.operation({ op: 'group_create', label: 'research' }); await admin.operation({ op: 'group_create', label: 'other' });
    for (const name of ['alice', 'bob', 'carol', 'outside']) await admin.operation({ op: 'user_create', username: name, name, password: '1', groups: [name === 'outside' ? 'local_other' : 'local_research'], contentAdminGroups: name === 'alice' ? ['local_research'] : [] });
    const connect = async (name: string) => { const wb = new Workbench(path.join(root, name), () => {}, () => {}); clients.push(wb); await wb.store.init(); await wb.configureWorkspace(memberProfile(admin.snapshot.profile!, admin.snapshot.state!, name), '1', root, async () => false); return wb; };
    const alice = await connect('alice');
    const project = await alice.createProject('任务验证', 'local_research', { background: '项目背景', objectives: '改善 OCR', acceptance: '覆盖失败样本', scope: '', deliverables: '', resources: '', constraints: '', collaboration: '' });
    const bob = await connect('bob'), carol = await connect('carol'), binding = alice.remote.binding(project.id), bobBinding = bob.remote.binding(project.id);
    const file = path.join(root, 'source.md'); await fs.writeFile(file, '依据');
    await alice.remote.upload(binding, file, binding.project.uploadPath + '/source.md', () => {}, { kind: 'contribution', title: 'OCR 基线结论', description: '低清晰度样本未覆盖，需要建立回归。' });
    const content = (await alice.remote.contentList(binding))[0];
    const input = { id: randomUUID(), title: '排查 OCR', description: '分析扫描件失败原因', acceptance: '补充回归样本', assignee: 'bob', references: [{ id: content.id, revision: content.revision }] };
    assert.deepEqual(new Set((await alice.remote.assignmentMembers(binding)).map(item => item.username)), new Set(['alice', 'bob', 'carol']));
    await assert.rejects(bob.remote.assignmentMembers(bobBinding), /子管理员/);
    await assert.rejects(bob.remote.assignmentCreate(bobBinding, input), /子管理员/);
    await assert.rejects(alice.remote.assignmentCreate(binding, { ...input, assignee: 'outside' }), /不属于/);
    await assert.rejects(alice.remote.assignmentCreate(binding, { ...input, references: [{ id: content.id, revision: 2 }] }), /结论已更新/);
    const task = await alice.remote.assignmentCreate(binding, input);
    assert.equal((await alice.remote.assignmentCreate(binding, input)).id, task.id, 'retry is idempotent');
    assert.equal((await alice.remote.assignmentList(binding)).length, 1);
    assert.deepEqual(await carol.remote.assignmentList(carol.remote.binding(project.id)), []);
    await assert.rejects(carol.remote.assignmentStatus(carol.remote.binding(project.id), { id: task.id, revision: 1, status: 'in_progress' }), /无权/);
    await assert.rejects(bob.remote.assignmentStatus(bobBinding, { id: task.id, revision: 1, status: 'cancelled' }), /子管理员/);
    await assert.rejects(bob.remote.assignmentStatus(bobBinding, { id: task.id, revision: 1, status: 'completed' }), /状态/);
    await assert.rejects(alice.startAssignment(project.id, task.id, 1, 'codex', root), /负责人/);
    await alice.editSharedContent(project.id, { id: content.id, revision: 1, action: 'delete', curate: true, merge: [] });
    assert.equal((await bob.remote.assignmentList(bobBinding))[0].references[0].content, content.description);
    const [session, duplicate] = await Promise.all([bob.startAssignment(project.id, task.id, 1, 'codex', root), bob.startAssignment(project.id, task.id, 1, 'codex', root)]);
    assert.equal(session.id, duplicate.id); assert.equal(bob.store.sessions.length, 1);
    assert.equal((await bob.startAssignment(project.id, task.id, 1, 'codex', root)).id, session.id);
    assert.equal(session.assignment?.sourceIds.length, 2); assert.equal(session.messages.length, 0, 'no model request on start');
    assert.match(bob.store.inputs[session.id].text, /扫描件失败/); assert.equal(bob.conclusions(project.id).length, 1);
    const context = sessionContext(session, '开始排查', []);
    for (const id of session.assignment!.sourceIds) assert(context.sources.some(item => item.id === id), 'task sources automatically enter context');
    const source = session.sources.find(item => item.sourcePath.includes(':content:'))!; assert.match(await fs.readFile(source.localPath, 'utf8'), /低清晰度/);
    const active = (await bob.remote.assignmentList(bobBinding))[0]; assert.equal(active.status, 'in_progress');
    await assert.rejects(bob.remote.assignmentStatus(bobBinding, { id: task.id, revision: 1, status: 'completed' }), /已更新/);
    await bob.remote.assignmentStatus(bobBinding, { id: task.id, revision: active.revision, status: 'completed' });
    assert.equal((await alice.remote.assignmentList(binding))[0].status, 'completed');
    const cancel = await alice.remote.assignmentCreate(binding, { ...input, id: randomUUID(), references: [] });
    await alice.remote.assignmentStatus(binding, { id: cancel.id, revision: cancel.revision, status: 'cancelled' });
    await assert.rejects(bob.startAssignment(project.id, cancel.id, 2, 'codex', root), /取消/);
    await bob.close(); const restored = new Workbench(bob.store.root, () => {}, () => {}); clients.push(restored); await restored.store.init();
    assert.deepEqual(restored.session(session.id).assignment, session.assignment); assert.equal(restored.conclusions(project.id).length, 1);
  } finally { for (const client of clients) await client.close(); admin.disconnect(); assert(root.startsWith(path.join(os.tmpdir(), 'wb-assignments-'))); await fs.rm(root, { recursive: true, force: true, maxRetries: 5 }); }
});
