import { offlineSettings, offlineProjectId } from '../tests/fixtures/offline-workspace.mjs';
import { _electron as electron, expect as baseExpect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { authLauncher } from '../tests/fixtures/auth-launcher.mjs';
const expect = baseExpect.configure({ timeout: 25000 });
const root = process.cwd(), data = path.join(root, '.test-data', 'permissions-ui-' + Date.now());
await fs.mkdir(data, { recursive: true });
const fixture = await authLauncher(path.join(data, 'cli'), { status: 'ready', permissionRuntime: true, permissionConfig: { sandbox: 'read-only', approval: 'never' }, toolApproval: true });
const cursorConfig = path.join(data, 'cursor-config'); await fs.mkdir(cursorConfig);
const globalFile = path.join(cursorConfig, 'cli-config.json');
await fs.writeFile(globalFile, JSON.stringify({ version: 1, approvalMode: 'unrestricted', permissions: { allow: ['Shell(*)'], deny: ['Read(.env)'] }, auth: { token: 'PRIVATE' } }));
await fs.writeFile(path.join(data, 'settings.json'), JSON.stringify({ ...offlineSettings(), connections: [], providerPaths: { codex: fixture.launcher, cursor: fixture.launcher }, lastWorkspace: data, localWorkspace: data, verifiedLocalWorkspace: data }));
const env = { ...process.env, WORKBENCH_TEST: '1', WORKBENCH_DATA_DIR: data, CURSOR_CONFIG_DIR: cursorConfig }; delete env.ELECTRON_RUN_AS_NODE;
const app = await electron.launch({ args: ['dist/user'], cwd: root, env, timeout: 60000 });
const artifacts = path.join(root, 'artifacts'); await fs.mkdir(artifacts, { recursive: true });
try {
  const page = await app.firstWindow(), errors = []; page.on('pageerror', e => errors.push(e.message));
  const call = (action, payload) => page.evaluate(([a, p]) => window.workbench.call(a, p), [action, payload]);
  const snap = () => call('snapshot');
  const calls = async () => (await fs.readFile(path.join(data, 'cli/rpc-calls.jsonl'), 'utf8')).trim().split('\n').map(x => JSON.parse(x));
  const send = async text => { await page.getByLabel('任务输入', { exact: true }).fill(text); await page.getByRole('button', { name: '发送任务', exact: true }).click(); };
  await page.getByRole('button', { name: '新建工作会话', exact: true }).click();
  await expect(page.getByLabel('权限模式')).toHaveValue('inherit');
  await expect(page.getByLabel('CLI 执行权限')).toContainText('审批已关闭');
  await page.getByLabel('权限模式').selectOption('review');
  await expect(page.getByLabel('Codex 登录状态').getByText('fake@example.com')).toBeVisible();
  await page.screenshot({ path: path.join(artifacts, 'permissions-create.png') });
  await page.getByRole('button', { name: '创建会话', exact: true }).click();
  await expect(page.getByRole('heading', { name: '新建工作会话', exact: true })).toHaveCount(0);
  const first = (await snap()).sessions[0]; assert.equal(first.permissionMode, 'review');
  await send('请求需要审核的操作');
  await expect(page.getByLabel('待授权提醒')).toContainText('1');
  await expect(page.locator('.approval')).toContainText('Codex 请求执行命令');
  const second = await call('session.create', { provider: 'codex', cwd: data, projectId: offlineProjectId });
  await page.locator(`.session-row[data-session-id="${second.id}"]`).click();
  await expect(page.locator('.approval')).toHaveCount(0);
  await page.getByLabel('待授权提醒').getByRole('button').click();
  await page.locator('.approval > details > summary').click();
  await expect(page.locator('.approval')).toContainText('test command');
  await page.screenshot({ path: path.join(artifacts, 'permissions-approval.png') });
  await page.locator('.approval').getByRole('button', { name: '允许本次', exact: true }).click();
  await expect.poll(async () => (await snap()).sessions.find(s => s.id === first.id).status).toBe('idle');
  await expect(page.getByLabel('待授权提醒')).toHaveCount(0);
  await fixture.write({ status: 'ready', permissionRuntime: true, permissionDenied: 'Windows sandbox: CreateProcessWithLogonW failed: 1385' });
  await send('验证运行中权限错误');
  await expect(page.locator('.permission-alert')).toContainText('执行遇到权限限制');
  await page.getByRole('button', { name: '查看权限与处理方式', exact: true }).click();
  await page.getByLabel('权限模式').selectOption('full');
  await page.setViewportSize({ width: 1100, height: 760 });
  const apply = page.getByRole('button', { name: '应用到此会话', exact: true });
  await apply.scrollIntoViewIfNeeded(); const box = await apply.boundingBox(); assert(box && box.y >= 0 && box.y + box.height <= 760);
  await page.screenshot({ path: path.join(artifacts, 'permissions-change.png') });
  const turnsBefore = (await calls()).filter(m => m.method === 'turn/start').length;
  await apply.click();
  await expect(page.getByRole('heading', { name: '会话执行权限', exact: true })).toHaveCount(0);
  assert.equal((await calls()).filter(m => m.method === 'turn/start').length, turnsBefore, 'changing policy must not replay work');
  const changed = (await snap()).sessions.find(s => s.id === first.id);
  assert.equal(changed.nativeId, first.nativeId || 'fake-thread'); assert.equal(changed.permissionMode, 'full'); assert.equal(changed.permissionIssue, undefined);
  await fixture.write({ status: 'ready', permissionRuntime: true, turn: 'success' });
  await send('用户主动继续');
  await expect.poll(async () => (await snap()).sessions.find(s => s.id === first.id).permissions?.sandbox).toBe('dangerFullAccess');
  await expect.poll(async () => (await snap()).sessions.find(s => s.id === first.id).status).toBe('idle');
  assert((await calls()).some(m => m.method === 'thread/resume' && m.params.sandbox === 'danger-full-access' && m.params.approvalPolicy === 'never'));
  // Even a full-mode runtime can receive team-enforced requests; never auto-answer.
  await fixture.write({ status: 'ready', permissionRuntime: true, toolApproval: true }); await send('仍需团队批准的操作');
  await expect(page.locator('.approval')).toBeVisible();
  const oldRequest = (await snap()).sessions.find(s => s.id === first.id).approvals[0];
  await page.getByRole('button', { name: '检测与修改权限', exact: true }).click();
  await page.getByLabel('权限模式').selectOption('review');
  await page.getByRole('button', { name: '停止当前任务并应用', exact: true }).click();
  await expect(page.getByRole('heading', { name: '会话执行权限', exact: true })).toHaveCount(0);
  await expect(page.getByLabel('待授权提醒')).toHaveCount(0);
  await assert.rejects(call('session.answer', { id: first.id, requestId: oldRequest.id, option: 'accept' }));
  assert.equal((await snap()).sessions.find(s => s.id === first.id).status, 'idle');
  // Cursor configuration changes are explicit and limited to isolated test paths.
  await page.setViewportSize({ width: 1520, height: 980 });
  await page.getByRole('button', { name: '新建会话', exact: true }).click();
  await page.getByRole('button', { name: 'Cursor', exact: true }).click();
  await page.getByLabel('权限模式').selectOption('review');
  await page.getByText('配置 Cursor 人工审批', { exact: true }).click();
  await expect(page.getByLabel('CLI 执行权限')).toContainText('会影响使用同一配置的其他 Cursor CLI 会话');
  assert.equal(JSON.parse(await fs.readFile(globalFile, 'utf8')).approvalMode, 'unrestricted');
  await page.getByRole('button', { name: '应用 Cursor 人工审批配置', exact: true }).click();
  await expect.poll(async () => JSON.parse(await fs.readFile(globalFile, 'utf8')).approvalMode).toBe('allowlist');
  const configured = JSON.parse(await fs.readFile(globalFile, 'utf8')); assert.deepEqual(configured.permissions.allow, []); assert.deepEqual(configured.permissions.deny, ['Read(.env)']); assert.equal(configured.auth.token, 'PRIVATE');
  await expect(page.getByLabel('Cursor 登录状态').getByText('fake@example.com')).toBeVisible();
  await page.screenshot({ path: path.join(artifacts, 'permissions-cursor.png') });
  await page.getByRole('button', { name: '创建会话', exact: true }).click();
  const cursor = (await snap()).sessions.find(s => s.provider === 'cursor'); assert.equal(cursor.permissionMode, 'review');
  await expect(page.getByRole('heading', { name: '新建工作会话', exact: true })).toHaveCount(0);
  await expect(page.locator(`.session-row[data-session-id="${cursor.id}"]`)).toHaveClass(/selected/);
  await send('Cursor 人工审批');
  await expect(page.locator('.approval')).toContainText('Cursor 请求执行命令');
  await assert.rejects(call('provider.cursorReview', { cwd: data, projectId: offlineProjectId }), /先停止/);
  await expect(page.locator('.approval').getByRole('button')).toHaveCount(2);
  await page.locator('.approval').getByRole('button', { name: '拒绝', exact: true }).click();
  await expect.poll(async () => (await snap()).sessions.find(s => s.id === cursor.id).status).toBe('idle');
  assert.deepEqual(errors, []);
  console.log('Permission UI passed: default inherited policy, readonly/never warnings, manual Codex and Cursor approval, background-session notification routing, allow/deny, sandbox failure, explicit session change/resume, no replay, stop pending approval, stale answer rejected, isolated Cursor config backup and deny preservation, compact window layout.');
} catch (e) { await (await app.firstWindow()).screenshot({ path: path.join(artifacts, 'permissions-failed.png') }).catch(() => {}); throw e; }
finally { await app.close(); }
