import { releaseRoot } from './release-paths.mjs';
import { _electron as electron, expect } from '@playwright/test';
import electronPath from 'electron';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { teamServer } from '../tests/fixtures/team-server.mjs';
import { adminCases } from './admin-cases.mjs';
import { usabilityCases, restoredCases } from './usability-cases.mjs';
import { authLauncher } from '../tests/fixtures/auth-launcher.mjs';
import { completeProjectSetup } from './onboarding-helpers.mjs';
const root = process.cwd();
const packaged = process.argv.includes('--packaged');
const launch = edition => packaged ? { executablePath: path.join(releaseRoot, edition, 'win-unpacked', edition === 'user' ? 'Team Agent User.exe' : 'Team Agent Admin.exe'), args: [] } : { args: ['dist/' + edition] };
const server = await teamServer();
const data = path.join(root, '.test-data', 'ui-' + Date.now());
await fs.mkdir(data, { recursive: true });
const auth = await authLauncher(path.join(data, 'fake-cli'));
await fs.writeFile(path.join(data, 'settings.json'), JSON.stringify({ connections: [], providerPaths: { codex: auth.launcher, cursor: auth.launcher }, lastWorkspace: '' }));
const env = { ...process.env, WORKBENCH_TEST: '1', WORKBENCH_DATA_DIR: data };
delete env.ELECTRON_RUN_AS_NODE;
let expected;
const app = await electron.launch({ ...launch('user'), cwd: root, env, timeout: 60000 });
try {
  const page = await app.firstWindow();
  const admin = await electron.launch({ ...launch('admin'), cwd: root, env: { ...env, WORKBENCH_ADMIN_DATA_DIR: data + '-admin' }, timeout: 60000 });
  try {
    const adminPage = await admin.firstWindow();
    await adminPage.getByText('管理员服务器连接', { exact: true }).waitFor();
    if (!packaged) await adminPage.screenshot({ path: path.join(data, 'admin-connection.png') });
    await adminPage.getByRole('button', { name: '取消', exact: true }).click();
    await adminPage.locator('.admin-deferred').waitFor();
    if (!packaged) await adminPage.screenshot({ path: path.join(data, 'admin-main.png') });
    const isolation = await adminPage.evaluate(async () => ({ userAPI: typeof window.workbench, denied: await window.admin.call('session.create').then(() => false, () => true) }));
    assert.deepEqual(isolation, { userAPI: 'undefined', denied: true });
    assert.equal(await page.evaluate(() => typeof window.admin), 'undefined');
    const userData = await app.evaluate(({ app }) => app.getPath('userData'));
    const adminData = await admin.evaluate(({ app }) => app.getPath('userData'));
    assert.notEqual(userData, adminData);
    console.log('Concurrent windows, isolated APIs and independent data paths verified.');
    await adminCases({ app: admin, page: adminPage, data });
  } finally { await admin.close(); }
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.getByText('登录团队工作台', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '登录', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByText('先连接团队账号', { exact: true }).waitFor();
  await assert.rejects(page.evaluate(cwd => window.workbench.call('session.create', { provider: 'codex', cwd }), data));
  await page.getByRole('button', { name: '连接团队账号', exact: true }).click();
  const profile = server.profile('alice');
  await page.getByLabel('本机工作路径', { exact: true }).fill(data);
  assert.equal(await page.getByLabel('Linux 工作路径', { exact: true }).count(), 0);
  await page.getByLabel('服务器地址', { exact: true }).fill(profile.host);
  await page.getByLabel('SFTP 端口', { exact: true }).fill(String(profile.port));
  await page.getByLabel('成员账号', { exact: true }).fill(profile.username);
  await page.getByLabel('登录密码', { exact: true }).fill('wrong-password');
  await app.evaluate(({ dialog }) => {
    const original = dialog.showMessageBox.bind(dialog);
    globalThis.__serverIdentityPrompts = 0;
    dialog.showMessageBox = async (window, options) => {
      if (options?.title === '首次连接团队服务器') { globalThis.__serverIdentityPrompts++; return { response: 1, checkboxChecked: false }; }
      return original(window, options);
    };
  });
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.getByRole('alert').filter({ hasText: 'authentication' }).waitFor();
  assert.equal(await page.getByText('先连接团队账号', { exact: true }).count(), 1);
  await page.getByLabel('登录密码', { exact: true }).fill('test-password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await completeProjectSetup(page, '实体抽取');
  assert.equal(await app.evaluate(() => globalThis.__serverIdentityPrompts), 1);
  const duplicateLaunch = launch('user');
  const duplicate = spawn(packaged ? duplicateLaunch.executablePath : electronPath, packaged ? [] : ['dist/user'], { cwd: root, env, windowsHide: true, stdio: 'ignore' });
  const exitCode = await new Promise((resolve, reject) => { const timer = setTimeout(() => { duplicate.kill(); reject(new Error('duplicate user instance did not exit')); }, 10000); duplicate.on('exit', code => { clearTimeout(timer); resolve(code); }); duplicate.on('error', reject); });
  assert.equal(exitCode, 0); await expect.poll(() => app.windows().length).toBe(2);
  const secondUser = app.windows().find(candidate => candidate !== page);
  await secondUser.getByText('登录团队工作台', { exact: true }).waitFor();
  const bobProfile = server.profile('bob');
  await secondUser.evaluate(([profile, localPath]) => window.workbench.call('remote.connect', { profile, password: 'test-password', localPath }), [bobProfile, data]);
  assert.equal((await page.evaluate(() => window.workbench.call('snapshot'))).connection.profile.username, 'alice');
  assert.equal((await secondUser.evaluate(() => window.workbench.call('snapshot'))).connection.profile.username, 'bob');
  assert.equal(await app.evaluate(() => globalThis.__serverIdentityPrompts), 1);
  await secondUser.close(); await expect.poll(() => app.windows().length).toBe(1);
  await page.locator('.workgroup-project').filter({ hasText: '实体抽取' }).click();
  assert(server.nodes.has('/projects/ocr/实体抽取/trajectories'));
  await page.getByRole('button', { name: '新建工作会话', exact: true }).waitFor();
  await fs.mkdir(path.join(root, 'artifacts'), { recursive: true });
  if (!packaged) await page.screenshot({ path: path.join(root, 'artifacts', 'welcome.png') });
  await page.getByRole('button', { name: '新建工作会话', exact: true }).click();
  await page.getByLabel('本地工作目录', { exact: true }).fill(data);
  await page.getByLabel('Codex 登录状态', { exact: true }).getByText('未登录', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '创建会话', exact: true }).isDisabled(), true);
  await assert.rejects(page.evaluate(cwd => window.workbench.call('session.create', { provider: 'codex', cwd }), data), /尚未登录/);
  await page.getByRole('button', { name: 'Cursor', exact: true }).click();
  const cursorAuth = page.getByLabel('Cursor 登录状态', { exact: true });
  await cursorAuth.getByText('未登录', { exact: true }).waitFor();
  if (!packaged) await page.screenshot({ path: path.join(root, 'artifacts', 'auth-not-logged-in.png') });
  await cursorAuth.getByRole('button', { name: '登录个人账号', exact: true }).click();
  await cursorAuth.getByText('已登录', { exact: true }).waitFor();
  await auth.write({ status: 'network' });
  await cursorAuth.getByRole('button', { name: '重新检测', exact: true }).click();
  await cursorAuth.getByText('检测失败', { exact: true }).waitFor();
  assert.equal(await cursorAuth.getByText('未登录', { exact: true }).count(), 0);
  if (!packaged) await page.screenshot({ path: path.join(root, 'artifacts', 'auth-network-error.png') });
  await auth.write({ status: 'ready' });
  await page.getByRole('button', { name: 'Codex · GPT', exact: true }).click();
  await page.getByLabel('Codex 登录状态', { exact: true }).getByText('已登录', { exact: true }).waitFor();
  await page.getByRole('button', { name: '创建会话', exact: true }).click();
  await page.getByLabel('任务输入', { exact: true }).waitFor();
  await auth.write({ status: 'none' });
  await page.evaluate(cwd => window.workbench.call('provider.auth', { provider: 'codex', cwd }), data);
  await page.getByLabel('任务输入', { exact: true }).fill('登录前保留这段任务');
  await page.getByRole('button', { name: '发送任务', exact: true }).click();
  await page.locator('.toast').filter({ hasText: '尚未登录' }).waitFor();
  assert.equal(await page.getByLabel('任务输入', { exact: true }).inputValue(), '登录前保留这段任务');
  await page.getByLabel('Codex 登录状态', { exact: true }).getByRole('button', { name: '登录个人账号', exact: true }).click();
  await page.getByLabel('Codex 登录状态', { exact: true }).waitFor({ state: 'detached' });
  assert.equal(await page.getByLabel('任务输入', { exact: true }).inputValue(), '登录前保留这段任务');
  assert(!(await auth.calls()).includes('turn/start'));
  if (!await page.getByRole('button', { name: '查看阶段摘要', exact: true }).isVisible()) await page.locator('.session-materials > summary').click(); await page.getByRole('button', { name: '查看阶段摘要', exact: true }).click(); await page.getByRole('button', { name: '更正摘要', exact: true }).click();
  await page.locator('.handoff-editor').fill('# 交接\n\n已实现目录浏览。验证：本地 UI 检查通过。\n');
  await page.getByRole('button', { name: '保存并返回', exact: true }).click();
  await page.getByRole('button', { name: '轨迹上传', exact: true }).click();
  assert.equal(await page.locator('.check-row input').isChecked(), false);
  await page.getByRole('button', { name: '关闭窗口', exact: true }).click();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByText('设置', { exact: true }).waitFor();
  await page.getByRole('tab', { name: '本机与 CLI', exact: true }).click();
  await page.getByText('Codex · GPT', { exact: true }).waitFor();
  if (!packaged) await page.screenshot({ path: path.join(root, 'artifacts', 'settings.png') });
  await page.getByRole('button', { name: '关闭窗口', exact: true }).click();
  await page.locator('.connection-button').click();
  await page.getByLabel('服务器地址', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('服务器地址', { exact: true }).inputValue(), profile.host);
  if (!packaged) await page.screenshot({ path: path.join(root, 'artifacts', 'connection.png') });
  await page.getByRole('button', { name: '取消', exact: true }).click();
  const state = await page.evaluate(() => window.workbench.call('snapshot'));
  assert.equal(state.sessions.length, 1);
  assert.equal(state.sessions[0].autoUpload, false);
  assert.equal(state.sessions[0].nativeId, undefined);
  assert.deepEqual(errors, []);
  console.log(packaged ? 'Packaged EXE:' : 'Development build:', 'UI smoke passed: workspace/project setup, provider selection, login gating and recovery, network errors, preserved input, handoff and history defaults.');
  expected = await usabilityCases({ page, app, data, auth, profile });
  await page.getByTitle('上传文件到当前目录', { exact: true }).click();
  const disconnected = page.locator('.toast').filter({ hasText: '连接已断开' });
  await disconnected.getByRole('button', { name: '连接团队账号', exact: true }).click();
  await page.getByText('登录团队工作台', { exact: true }).waitFor();
  await page.getByRole('button', { name: '取消', exact: true }).click();
} catch (error) {
  console.error('UI case failed:', error);
  // A deliberately failed save can correctly block normal quit. Force only this test instance closed.
  await app.evaluate(({ app }) => app.exit(1)).catch(() => {});
  throw error;
} finally { await app.close(); await server.close(); }
const restored = await electron.launch({ ...launch('user'), cwd: root, env, timeout: 60000 });
try { await restoredCases(await restored.firstWindow(), expected); } finally { await restored.close(); }
