import { _electron as electron } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
const root = process.cwd();
const data = path.join(root, '.test-data', 'ui-' + Date.now());
await fs.mkdir(data, { recursive: true });
const env = { ...process.env, WORKBENCH_TEST: '1', WORKBENCH_DATA_DIR: data };
delete env.ELECTRON_RUN_AS_NODE;
const app = await electron.launch({ args: ['dist/user'], cwd: root, env, timeout: 60000 });
try {
  const page = await app.firstWindow();
  const admin = await electron.launch({ args: ['dist/admin'], cwd: root, env: { ...env, WORKBENCH_ADMIN_DATA_DIR: data + '-admin' }, timeout: 60000 });
  try {
    const adminPage = await admin.firstWindow();
    await adminPage.getByText('管理员服务器连接', { exact: true }).waitFor();
    await adminPage.screenshot({ path: path.join(data, 'admin-connection.png') });
    await adminPage.getByRole('button', { name: '取消', exact: true }).click();
    await adminPage.locator('.admin-deferred').waitFor();
    await adminPage.screenshot({ path: path.join(data, 'admin-main.png') });
    const isolation = await adminPage.evaluate(async () => ({ userAPI: typeof window.workbench, denied: await window.admin.call('session.create').then(() => false, () => true) }));
    assert.deepEqual(isolation, { userAPI: 'undefined', denied: true });
    assert.equal(await page.evaluate(() => typeof window.admin), 'undefined');
    const userData = await app.evaluate(({ app }) => app.getPath('userData'));
    const adminData = await admin.evaluate(({ app }) => app.getPath('userData'));
    assert.notEqual(userData, adminData);
    console.log('Concurrent windows, isolated APIs and independent data paths verified.');
  } finally { await admin.close(); }
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.getByText('连接团队共享空间', { exact: true }).waitFor();
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: '新建工作会话', exact: true }).waitFor();
  await fs.mkdir(path.join(root, 'artifacts'), { recursive: true });
  await page.screenshot({ path: path.join(root, 'artifacts', 'welcome.png') });
  await page.getByRole('button', { name: '新建工作会话', exact: true }).click();
  await page.getByLabel('本地工作目录', { exact: true }).fill(data);
  await page.getByRole('button', { name: '创建会话', exact: true }).click();
  await page.getByLabel('任务输入', { exact: true }).waitFor();
  await page.getByRole('button', { name: '交接文件', exact: true }).click();
  await page.locator('.handoff-editor').fill('# 交接\n\n已实现目录浏览。验证：本地 UI 检查通过。\n');
  await page.getByRole('button', { name: '保存交接文件', exact: true }).click();
  await page.getByRole('button', { name: '会话归档', exact: true }).click();
  assert.equal(await page.locator('.check-row input').isChecked(), false);
  await page.getByRole('button', { name: '关闭窗口', exact: true }).click();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByText('CLI 与本地设置', { exact: true }).waitFor();
  await page.screenshot({ path: path.join(root, 'artifacts', 'settings.png') });
  await page.getByRole('button', { name: '关闭窗口', exact: true }).click();
  await page.getByRole('button', { name: '配置连接', exact: true }).click();
  await page.getByText('使用管理员分配的 Linux 账号密码。', { exact: false }).waitFor();
  await page.screenshot({ path: path.join(root, 'artifacts', 'connection.png') });
  await page.getByRole('button', { name: '取消', exact: true }).click();
  const state = await page.evaluate(() => window.workbench.call('snapshot'));
  assert.equal(state.sessions.length, 1);
  assert.equal(state.sessions[0].autoUpload, false);
  assert.equal(state.sessions[0].nativeId, undefined);
  assert.deepEqual(errors, []);
  console.log('UI smoke passed: startup, session creation, handoff editing, history defaults, settings and connection form.');
} finally { await app.close(); }
