import React, { useEffect, useState } from 'react';
import { Activity, CircleCheck, Clipboard, KeyRound, Network, RefreshCw, ShieldCheck, WifiOff } from 'lucide-react';
import type { AdminEgressConfig, AdminEgressSnapshot } from '../shared/egress';

const api = window.admin;
const stamp = (value: string) => { try { return new Date(value).toLocaleString(); } catch { return value; } };
const traffic = (value: number) => value < 1024 ? value + ' B' : value < 1024 ** 2 ? (value / 1024).toFixed(1) + ' KB' : (value / 1024 ** 2).toFixed(1) + ' MB';

export function EgressView({ snapshot, refresh }: { snapshot: AdminEgressSnapshot; refresh: () => Promise<void> }) {
  const [config, setConfig] = useState(snapshot.config), [password, setPassword] = useState(''), [clearPassword, setClearPassword] = useState(false);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  useEffect(() => setConfig(snapshot.config), [JSON.stringify(snapshot.config)]);
  const update = <K extends keyof AdminEgressConfig>(key: K, value: AdminEgressConfig[K]) => setConfig(current => ({ ...current, [key]: value }));
  const run = async (fn: () => Promise<void>) => { setBusy(true); setError(''); setMessage(''); try { await fn(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const save = () => run(async () => { await api.call('egress.save', { config, upstreamPassword: password, clearUpstreamPassword: clearPassword }); setPassword(''); setClearPassword(false); await refresh(); setMessage(config.enabled ? '网络出口已保存并启动' : '网络出口已关闭，用户端可继续使用本机直连'); });
  return <div className="egress-view">
    <div className="page-title egress-title"><div><span className="eyebrow">NETWORK EGRESS</span><h1>网络出口</h1><p>为无法直接访问外网的成员转发 Codex 和 Cursor 连接；成员仍使用自己的账号。</p></div><span className={'egress-state ' + (snapshot.running ? 'online' : '')}>{snapshot.running ? <CircleCheck size={17}/> : <WifiOff size={17}/>} {snapshot.running ? '出口运行中' : config.enabled ? '出口未运行' : '未启用'}</span></div>
    {error && <div className="inline-error" role="alert">{error}</div>}{message && <div className="admin-success"><CircleCheck size={17}/>{message}</div>}
    <div className="egress-stat-grid"><div><Network size={19}/><span>监听地址</span><strong>{config.publicHost}:{config.listenPort}</strong></div><div><Activity size={19}/><span>当前连接</span><strong>{snapshot.activeConnections}</strong></div><div><ShieldCheck size={19}/><span>传输保护</span><strong>加密隧道</strong></div><div><KeyRound size={19}/><span>上游方式</span><strong>{config.upstreamMode === 'direct' ? '直接访问' : config.upstreamMode === 'http' ? 'HTTP 代理' : 'SOCKS5'}</strong></div></div>
    {snapshot.lastError && <div className="inline-error">出口启动失败：{snapshot.lastError}</div>}
    <section className="egress-card"><header><div><h3>出口设置</h3><small>关闭后不会影响用户端本地工作和共享空间。</small></div><label className="switch-row"><input type="checkbox" checked={config.enabled} onChange={e => update('enabled', e.target.checked)}/>启用管理端出口</label></header><div className="egress-form">
      <div className="form-grid"><label className="field">提供给成员的地址<input aria-label="提供给成员的地址" value={config.publicHost} onChange={e => update('publicHost', e.target.value)}/><small>自动填入本机名；无法解析时改成固定内网 IP。</small></label><label className="field">监听端口<input aria-label="网络出口端口" type="number" value={config.listenPort} onChange={e => update('listenPort', Number(e.target.value))}/></label></div>
      <details><summary>监听与产品范围</summary><div className="form-grid egress-details"><label className="field">本机监听地址<input value={config.listenHost} onChange={e => update('listenHost', e.target.value)}/></label><div className="field"><span>允许的 CLI</span><label className="check-row"><input type="checkbox" checked={config.codex} onChange={e => update('codex', e.target.checked)}/>Codex · GPT</label><label className="check-row"><input type="checkbox" checked={config.cursor} onChange={e => update('cursor', e.target.checked)}/>Cursor</label></div></div></details>
      <label className="field">管理端如何访问外网<select aria-label="上游代理类型" value={config.upstreamMode} onChange={e => update('upstreamMode', e.target.value as AdminEgressConfig['upstreamMode'])}><option value="direct">本机直接访问</option><option value="http">HTTP 代理</option><option value="socks5">SOCKS5 代理</option></select></label>
      {config.upstreamMode !== 'direct' && <><div className="form-grid"><label className="field">代理地址<input aria-label="上游代理地址" placeholder="例如 127.0.0.1" value={config.upstreamHost} onChange={e => update('upstreamHost', e.target.value)}/></label><label className="field">代理端口<input aria-label="上游代理端口" type="number" value={config.upstreamPort || ''} onChange={e => update('upstreamPort', Number(e.target.value))}/></label></div><div className="form-grid"><label className="field">代理账号（没有则留空）<input value={config.upstreamUsername} onChange={e => update('upstreamUsername', e.target.value)}/></label><label className="field">代理密码<input type="password" autoComplete="new-password" placeholder={snapshot.hasUpstreamPassword ? '已安全保存，留空保持不变' : '没有则留空'} value={password} onChange={e => { setPassword(e.target.value); setClearPassword(false); }}/></label></div>{snapshot.hasUpstreamPassword && <label className="check-row"><input type="checkbox" checked={clearPassword} onChange={e => setClearPassword(e.target.checked)}/>清除已保存的代理密码</label>}</>}
    </div><footer><span className="spacer"/><button className="primary" disabled={busy} onClick={() => void save()}>{busy ? '正在应用…' : '保存并应用'}</button></footer></section>
    <section className="egress-card"><header><div><h3>用户端接入码</h3><small>复制给确实需要使用管理端出口的成员；其他成员继续直连。</small></div><button className="primary compact" onClick={() => void run(async () => { await api.call('egress.copy'); setMessage('接入码已复制'); })}><Clipboard size={15}/>复制接入码</button></header><div className="egress-invite"><code>{snapshot.inviteCode.slice(0, 28)}…</code><div><small>证书指纹</small><code>{snapshot.fingerprint.match(/.{1,4}/g)?.join(' ')}</code></div></div><footer><button className="secondary" disabled={busy || !snapshot.running || !config.codex} onClick={() => void run(async () => { await api.call('egress.test', { provider: 'codex' }); setMessage('Codex 外网连接测试通过'); })}>测试 Codex</button><button className="secondary" disabled={busy || !snapshot.running || !config.cursor} onClick={() => void run(async () => { await api.call('egress.test', { provider: 'cursor' }); setMessage('Cursor 外网连接测试通过'); })}>测试 Cursor</button><span className="spacer"/><button className="text-button danger" disabled={busy} onClick={() => void run(async () => { await api.call('egress.rotate'); await refresh(); setMessage('接入码已更新，已接入成员需要重新配置'); })}><RefreshCw size={14}/>更新接入码</button></footer></section>
    <section className="egress-card"><header><div><h3>最近连接</h3><small>仅记录用户端上报的账号标识、产品、目标域名和流量，不保存提问、回答或个人账号凭据；账号标识不用于权限认证。</small></div></header><div className="storage-table-scroll"><table><thead><tr><th>时间</th><th>账号标识</th><th>产品</th><th>目标</th><th>状态</th><th>流量</th></tr></thead><tbody>{snapshot.events.length ? snapshot.events.map(event => <tr key={event.id}><td>{stamp(event.at)}</td><td>{event.username || '未标识'}</td><td>{event.provider === 'codex' ? 'Codex' : event.provider === 'cursor' ? 'Cursor' : '连接检测'}</td><td><code>{event.target || '管理端'}</code></td><td>{event.status === 'connected' ? '连接中' : event.status === 'closed' ? '已结束' : event.status === 'rejected' ? '已拒绝' : '失败'}{event.detail && <small>{event.detail}</small>}</td><td>↑ {traffic(event.bytesUp)} · ↓ {traffic(event.bytesDown)}</td></tr>) : <tr><td className="storage-no-rows" colSpan={6}>还没有成员通过管理端出口连接</td></tr>}</tbody></table></div></section>
  </div>;
}
