import React, { useState } from 'react';
import type { AccountSyncState } from '../shared/account-data';

export function AccountSyncStatus({ state, connected }: { state?: AccountSyncState; connected: boolean }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const labels = { offline: '本机已保存', pending: '资料待同步', syncing: '资料同步中', synced: '资料已同步', error: '资料同步失败', conflict: '资料版本待确认' };
  const run = async (action: string, input?: unknown) => { setBusy(true); setError(''); try { await window.workbench.call(action, input); } catch (error: any) { setError(error.message); } finally { setBusy(false); } };
  const describe = (value: any) => value == null ? '已删除' : typeof value === 'string' ? value : [value.title || '', value.content || value.body || JSON.stringify(value, null, 2)].join('\n');
  return <><button className="text-button" title={state?.detail || '个人账号资料同步状态'} onClick={() => setOpen(true)}>{labels[connected ? state?.status || 'offline' : 'offline']}</button>{open && <div className="modal-backdrop"><section className="modal wide" role="dialog" aria-modal="true" aria-label="账号资料同步"><header><h2>账号资料同步</h2><button className="icon" onClick={() => setOpen(false)} aria-label="关闭同步状态">×</button></header><div className="modal-body"><p>“本地项目成果库”、整理结果、分类组合、已选附件和动态处理记录仅向你的账号同步。Session、完整对话、代码目录和登录凭据只留在本机。</p>{state?.detail && <p role="status">{state.detail}</p>}{state?.syncedAt && <p className="muted small">最近同步：{new Date(state.syncedAt).toLocaleString()}</p>}{error && <p className="inline-error">{error}</p>}{state?.status === 'conflict' && state.conflicts?.map(conflict => <section key={conflict.key}><h3>{conflict.key === 'result-rules:preferences' ? '成果分类组合有两个版本' : '同一份资料有两个版本'}</h3><div className="form-grid"><div><b>本机版本</b><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 240, overflow: 'auto' }}>{describe(conflict.local)}</pre><button className="secondary" disabled={busy} onClick={() => void run('account.sync.resolve', { key: conflict.key, choice: 'local' })}>保留本机版本</button></div><div><b>账号中的版本</b><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 240, overflow: 'auto' }}>{describe(conflict.remote)}</pre><button className="secondary" disabled={busy} onClick={() => void run('account.sync.resolve', { key: conflict.key, choice: 'remote' })}>使用账号版本</button></div></div></section>)}</div><footer><button className="primary" disabled={busy || !connected || state?.status === 'syncing'} onClick={() => void run('account.sync')}>{busy ? '同步中…' : '立即同步'}</button></footer></section></div>}</>;
}
