import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Archive, Check, Sparkles, Plus, RotateCcw, Trash2 } from 'lucide-react';
import type { AgentSession, Draft, Project, ProjectConclusion } from '../shared/types';
import { attachedConclusion, conclusionTitle } from '../shared/conclusion-context';

const api = window.workbench;

export function ConclusionLibrary({ project, sessions, notice, mergeStarted, focusId, focusHandled }: { project: Project; sessions: AgentSession[]; notice: (text: string) => void; mergeStarted: (draft: Draft) => void; focusId?: string; focusHandled?: () => void }) {
  const [items, setItems] = useState<ProjectConclusion[]>([]), [selected, setSelected] = useState(''), [showArchived, setShowArchived] = useState(false);
  const [editing, setEditing] = useState(false), [creating, setCreating] = useState(false), [title, setTitle] = useState(''), [content, setContent] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [mergeSelection, setMergeSelection] = useState<string[]>([]);
  const [confirmingMerge, setConfirmingMerge] = useState(false), [instruction, setInstruction] = useState(''), [mergeSessionId, setMergeSessionId] = useState('');
  const [attaching, setAttaching] = useState<ProjectConclusion>(), [attachSelection, setAttachSelection] = useState<string[]>([]), [attachedIds, setAttachedIds] = useState<string[]>([]);
  const [aliasItem, setAliasItem] = useState<ProjectConclusion>(), [aliasValue, setAliasValue] = useState(''), [aliasError, setAliasError] = useState('');
  const [pendingDelete, setPendingDelete] = useState<ProjectConclusion[]>([]), [deleteError, setDeleteError] = useState('');
  const [selectingDelete, setSelectingDelete] = useState(false), [deleteSelection, setDeleteSelection] = useState<string[]>([]);
  const remove = async () => {
    if (!pendingDelete.length) return; setBusy(true); setDeleteError('');
    try {
      await api.call('conclusion.deleteMany', { selections: pendingDelete.map(value => ({ id: value.id, version: value.version })) });
      const removed = new Set(pendingDelete.map(value => value.id));
      setItems(current => current.filter(value => !removed.has(value.id)));
      setMergeSelection(current => current.filter(id => !removed.has(id)));
      if (removed.has(selected)) setSelected('');
      setPendingDelete([]); setDeleteSelection([]); setSelectingDelete(false); notice(`已删除 ${removed.size} 条本地结论，已有会话中的引用仍然保留`);
    } catch (e: any) { setDeleteError(e.message); } finally { setBusy(false); }
  };
  const saveAlias = async (alias: string) => {
    if (!aliasItem) return; setBusy(true); setAliasError('');
    try { const saved = await api.call<ProjectConclusion>('conclusion.alias.save', { id: aliasItem.id, alias }); setItems(current => current.map(value => value.id === saved.id ? saved : value)); setAliasItem(undefined); notice(alias.trim() ? '结论别名已保存' : '结论别名已清除'); }
    catch (e: any) { setAliasError(e.message); } finally { setBusy(false); }
  };
  const attachSessions = sessions.filter(session => session.purpose === 'work' && session.binding?.project.id === project.id);
  const alreadyAttached = (session: AgentSession) => !!attaching && (!!attachedConclusion(session, attaching.id) || attachedIds.includes(session.id));
  const newSelection = attachSelection.filter(id => attachSessions.some(session => session.id === id && !session.closedAt && !alreadyAttached(session)));
  const attach = async () => {
    if (!attaching) return; setBusy(true); setError('');
    try {
      for (const id of newSelection) {
        await api.call('session.attachConclusion', { id, conclusionId: attaching.id });
        setAttachedIds(current => [...new Set([...current, id])]);
        setAttachSelection(current => current.filter(value => value !== id));
      }
      notice(`已加入 ${newSelection.length} 个会话，下次提问时自动带入上下文`); setAttaching(undefined);
    } catch (e: any) { setError(e.message); } finally { setBusy(false); }
  };
  const load = async () => { setBusy(true); try { setItems(await api.call<ProjectConclusion[]>('conclusion.list', { projectId: project.id, includeArchived: true })); setError(''); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  useEffect(() => { setItems([]); setSelected(''); setCreating(false); setAliasItem(undefined); setPendingDelete([]); setSelectingDelete(false); setDeleteSelection([]); setMergeSelection([]); setConfirmingMerge(false); setInstruction(''); void load(); }, [project.id]);
  useEffect(() => { if (!sessions.some(session => session.id === mergeSessionId)) setMergeSessionId(sessions[0]?.id || ''); }, [sessions, mergeSessionId]);
  useEffect(() => { if (!focusId || !items.some(item => item.id === focusId)) return; setShowArchived(true); open(items.find(item => item.id === focusId)!); focusHandled?.(); }, [focusId, items]);
  const item = items.find(value => value.id === selected), visible = items.filter(value => showArchived || !value.archived);
  const selectedDeleteItems = visible.filter(value => deleteSelection.includes(value.id));
  const selectedMergeItems = visible.filter(value => !value.archived && mergeSelection.includes(value.id));
  const mergeReady = selectedMergeItems.length > 0 && selectedMergeItems.length <= 20;
  const sourceSummary = (value: ProjectConclusion) => !value.sources.length ? '手工记录' : [...new Set(value.sources.map(source => ({ session: '本地整理', remote: '共享区', conclusion: '本地结论', manual: '手工记录' })[source.kind]))].join('、');
  const open = (value: ProjectConclusion) => { setSelected(value.id); setCreating(false); setEditing(false); setTitle(value.title); setContent(value.content); };
  const beginCreate = () => { setSelected(''); setCreating(true); setEditing(true); setTitle(''); setContent(''); };
  const save = async () => {
    if (!title.trim() || !content.trim()) return; setBusy(true); setError('');
    try { const saved = creating ? await api.call<ProjectConclusion>('conclusion.create', { projectId: project.id, title, content }) : await api.call<ProjectConclusion>('conclusion.save', { id: item!.id, title, content }); setCreating(false); setEditing(false); await load(); setSelected(saved.id); notice(creating ? '本地结论已创建' : '本地结论已保存为新版本'); }
    catch (e: any) { setError(e.message); } finally { setBusy(false); }
  };
  const archive = async (value: ProjectConclusion, archived: boolean) => { setBusy(true); try { await api.call('conclusion.archive', { id: value.id, archived }); await load(); if (archived) { setSelected(''); setMergeSelection(current => current.filter(id => id !== value.id)); } notice(archived ? '结论已移入历史，不再推荐给新会话' : '结论已恢复使用'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const toggleMerge = (id: string, checked: boolean) => setMergeSelection(current => checked ? [...new Set([...current, id])] : current.filter(value => value !== id));
  const startMerge = async () => {
    setBusy(true); setError('');
    try { const draft = await api.call<Draft>('conclusion.merge.prepare', { projectId: project.id, sessionId: mergeSessionId, sourceIds: selectedMergeItems.map(value => value.id), instruction }); setConfirmingMerge(false); mergeStarted(draft); }
    catch (e: any) { setError(e.message); }
    finally { setBusy(false); }
  };
  return <div className="workspace-page conclusion-page">
    <div className="page-title"><div><span className="eyebrow">PERSONAL KNOWLEDGE</span><h1>个人结论库 · {project.name}</h1><p className="muted small">这里是保存在当前用户端本机的个人结论，按项目组织。可以手动填写或从团队动态加入；编辑和删除仅影响个人副本，不会修改团队共享区。</p></div><div className="row"><button className="secondary" disabled={busy} onClick={() => { setShowArchived(!showArchived); setDeleteSelection([]); setMergeSelection([]); }}>{showArchived ? '隐藏历史结论' : '显示历史结论'}</button><button className="secondary danger" disabled={busy || editing} onClick={() => { setSelectingDelete(!selectingDelete); setDeleteSelection([]); setMergeSelection([]); }}>{selectingDelete ? '取消多选' : '批量删除结论'}</button><button className="primary" disabled={busy || mergeSelection.length > 0 || selectingDelete} onClick={beginCreate}><Plus size={14}/>新建结论</button></div></div>
    {error && <div className="inline-error" role="alert">{error}</div>}
    <div className="callout conclusion-guide"><div><b>选择结论，按你的要求处理</b><small>直接勾选下方 1 至 20 条结论，再填写处理要求，例如提炼要点、对比差异、改写或合并。新会话首次提问时也可以选择已有结论作为参考。</small></div></div>
    {selectingDelete && <section className="semantic-merge-bar" aria-label="批量删除结论设置"><label className="check-row"><input type="checkbox" aria-label="全选当前结论" disabled={busy || !visible.length} checked={!!visible.length && selectedDeleteItems.length === visible.length} onChange={event => setDeleteSelection(event.target.checked ? visible.map(value => value.id) : [])}/><span>全选当前列表（{visible.length} 条）</span></label><span>已选择 {selectedDeleteItems.length} 条</span><button className="secondary danger" disabled={busy || !selectedDeleteItems.length} onClick={() => { setPendingDelete(selectedDeleteItems); setDeleteError(''); }}>删除选中的 {selectedDeleteItems.length} 条结论</button></section>}
    {!!selectedMergeItems.length && <section className="semantic-merge-bar" aria-label="结论处理设置"><div><b>已选择 {selectedMergeItems.length} 条结论</b><small>先生成预处理结果供你审阅和修改，确认保存前原结论保持不变。</small></div><button className="secondary" disabled={busy} onClick={() => setMergeSelection([])}>清空选择</button><button className="primary" disabled={busy || editing || !mergeReady} onClick={() => setConfirmingMerge(true)}>处理选中的 {selectedMergeItems.length} 条结论</button></section>}
    <div className="content-library conclusion-library"><div className="content-cards">{visible.map(value => <article className={'content-card ' + (value.id === selected ? 'selected' : '') + (mergeSelection.includes(value.id) || selectingDelete && deleteSelection.includes(value.id) ? ' merge-selected' : '')} key={value.id}>{selectingDelete && <label className="content-card-select check-row"><input type="checkbox" aria-label={`选择删除结论：${conclusionTitle(value)}`} checked={deleteSelection.includes(value.id)} disabled={busy} onChange={event => setDeleteSelection(current => event.target.checked ? [...new Set([...current, value.id])] : current.filter(id => id !== value.id))}/><span>选择删除</span></label>}{!selectingDelete && !value.archived && <label className="content-card-select check-row"><input type="checkbox" aria-label={`选择结论：${conclusionTitle(value)}`} checked={mergeSelection.includes(value.id)} disabled={busy || editing} onChange={event => toggleMerge(value.id, event.target.checked)}/><span>选择处理</span></label>}<button className="content-card-summary" disabled={editing} onClick={() => open(value)}><span className="content-category-badge">{value.archived ? '历史结论' : '使用中'}</span><b>{conclusionTitle(value)}</b>{value.titleAlias && <small>原名：{value.title}</small>}<small>v{value.version} · {sourceSummary(value)}{value.sources.length > 1 ? ` · ${value.sources.length} 个来源` : ''} · {new Date(value.updatedAt).toLocaleString()}</small><p>{value.content.slice(0, 140)}</p></button></article>)}{!visible.length && <div className="page-empty"><h2>还没有个人结论</h2><p>本地整理完成后会自动进入这里，也可以手工新建或从团队动态整理进来。</p></div>}</div>
      <section className="content-detail conclusion-detail">{editing ? <><h2>{creating ? '新建结论' : '编辑结论'}</h2><label className="field">标题<input aria-label="本地结论标题" value={title} maxLength={200} onChange={event => setTitle(event.target.value)}/></label><label className="field">内容<textarea aria-label="本地结论内容" rows={16} value={content} onChange={event => setContent(event.target.value)}/></label><div className="row"><button className="secondary" disabled={busy} onClick={() => { setCreating(false); setEditing(false); if (item) open(item); }}>取消</button><button className="primary" disabled={busy || !title.trim() || !content.trim()} onClick={() => void save()}><Check size={14}/>保存</button></div></> : item ? <><div className="content-detail-title"><span className="content-category-badge">{item.archived ? '历史结论' : '使用中'}</span><h2>{conclusionTitle(item)}</h2></div>{item.titleAlias && <p className="muted small">本地别名 · 原名：{item.title}</p>}<p className="muted small">v{item.version} · {sourceSummary(item)} · 更新于 {new Date(item.updatedAt).toLocaleString()}</p><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.content}</ReactMarkdown></div><details className="content-provenance"><summary>查看来源（{item.sources.length || 1}）</summary>{item.sources.length ? item.sources.map((source, index) => <p key={source.kind + ':' + source.id + ':' + index}>{({ session: '本地整理', remote: '共享区', conclusion: '本地结论', manual: '手工记录' })[source.kind]} · {source.title}{source.revision ? ` · v${source.revision}` : ''}{source.path ? ` · ${source.path}` : ''}</p>) : <p>本机手工记录</p>}</details><div className="row"><button className="secondary" disabled={busy} onClick={() => { setAliasItem(item); setAliasValue(item.titleAlias || ''); setAliasError(''); }}>设置本地别名</button><button className="secondary" disabled={busy} onClick={() => { setAttaching(item); setAttachSelection([]); setAttachedIds([]); setError(''); }}>加入会话</button>{item.archived ? <button className="secondary" onClick={() => void archive(item, false)}><RotateCcw size={14}/>恢复使用</button> : <><button className="primary" onClick={() => setEditing(true)}>编辑</button><button className="secondary" title="暂时停用，保留内容，可随时恢复" onClick={() => void archive(item, true)}><Archive size={14}/>移入历史</button></>}<button className="secondary danger" disabled={busy} onClick={() => { setPendingDelete([item]); setDeleteError(''); }}><Trash2 size={14}/>删除结论</button></div></> : <p className="muted">选择一条结论查看内容，或新建结论。</p>}</section></div>
    {pendingDelete.length > 0 && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-conclusion-title">
      <header><h2 id="delete-conclusion-title">删除本地结论？</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setPendingDelete([])}>×</button></header>
      <div className="modal-body"><p>将删除以下 {pendingDelete.length} 条本地结论，历史列表中也不再保留，无法通过“恢复使用”找回。</p><ul className="delete-selection-list">{pendingDelete.map(value => <li key={value.id}>{conclusionTitle(value)}{value.archived ? '（历史结论）' : ''}</li>)}</ul><p className="muted small">共享区内容和已经加入会话的引用保持不变。如果只是暂时不用，请取消并选择“移入历史”。</p>{deleteError && <div className="inline-error" role="alert">{deleteError}</div>}</div>
      <footer><button className="secondary" disabled={busy} onClick={() => setPendingDelete([])}>取消</button><button className="primary danger" disabled={busy} onClick={() => void remove()}>{busy ? '正在删除…' : pendingDelete.length === 1 ? '确认删除本地结论' : `确认删除 ${pendingDelete.length} 条本地结论`}</button></footer>
    </section></div>}
    {aliasItem && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="conclusion-alias-title">
      <header><h2 id="conclusion-alias-title">设置结论别名</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setAliasItem(undefined)}>×</button></header>
      <div className="modal-body"><p className="muted small">别名只影响本机显示，原名、内容和已加入会话的快照保持不变。</p>{aliasError && <div className="inline-error" role="alert">{aliasError}</div>}<label className="field">本地别名<input autoFocus aria-label="结论本地别名" maxLength={200} value={aliasValue} placeholder={aliasItem.title} onChange={event => setAliasValue(event.target.value)}/></label><p className="muted small">原名：{aliasItem.title}</p></div>
      <footer>{aliasItem.titleAlias && <button className="secondary danger" disabled={busy} onClick={() => void saveAlias('')}>清除别名</button>}<span className="spacer"/><button className="secondary" disabled={busy} onClick={() => setAliasItem(undefined)}>取消</button><button className="primary" disabled={busy || !aliasValue.trim()} onClick={() => void saveAlias(aliasValue)}>{busy ? '正在保存…' : '保存本地别名'}</button></footer>
    </section></div>}
    {attaching && <div className="modal-backdrop"><section className="modal attach-session-modal" role="dialog" aria-modal="true" aria-labelledby="attach-conclusion-title"><header><h2 id="attach-conclusion-title">选择使用结论的会话</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setAttaching(undefined)}>×</button></header><div className="modal-body"><p>{conclusionTitle(attaching)}</p><p className="muted small">已加入的会话会显示勾选，不能取消；新增会话下次提问时自动带入这份结论快照，不影响当前正在运行的任务。</p>{error && <div className="inline-error" role="alert">{error}</div>}<div className="attach-session-options">{attachSessions.map(session => { const used = alreadyAttached(session); return <label className="attach-session-option" key={session.id}><input type="checkbox" aria-label={`使用结论的会话：${session.title}`} checked={used || attachSelection.includes(session.id)} disabled={busy || used || !!session.closedAt || !!attaching.archived} onChange={e => setAttachSelection(current => e.target.checked ? [...new Set([...current, session.id])] : current.filter(id => id !== session.id))}/><span><b>{session.title}</b><small>{used ? '已加入上下文，不可取消' : session.closedAt ? '会话已关闭' : attaching.archived ? '请先恢复此结论' : '尚未使用'} · {session.provider === 'codex' ? 'Codex' : 'Cursor'}</small></span></label>; })}</div>{!attachSessions.length && <p className="muted">此项目还没有工作会话，请先创建。</p>}</div><footer><button className="secondary" disabled={busy} onClick={() => setAttaching(undefined)}>关闭</button><button className="primary" disabled={busy || !newSelection.length} onClick={() => void attach()}>{busy ? '正在加入…' : `加入 ${newSelection.length} 个会话`}</button></footer></section></div>}
    {confirmingMerge && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-conclusion-merge"><header><h2 id="confirm-conclusion-merge">处理所选结论</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setConfirmingMerge(false)}>×</button></header><div className="modal-body"><p>将根据你的要求处理所选 {selectedMergeItems.length} 条结论，生成一份预处理结果。你可以审阅和修改；只有确认保存为新结论后，所选原结论才会移入历史。</p>{error && <div className="inline-error" role="alert">{error}</div>}{sessions.length ? <label className="field">使用哪个会话的模型<select aria-label="用于处理结论的会话" value={mergeSessionId} disabled={busy} onChange={event => setMergeSessionId(event.target.value)}>{sessions.map(session => <option value={session.id} key={session.id}>{session.title} · {session.provider === 'codex' ? 'Codex' : 'Cursor'}</option>)}</select></label> : <p className="inline-error">请先为当前项目创建工作会话。</p>}<label className="field">处理要求（可选）<textarea aria-label="结论处理要求" rows={6} disabled={busy} placeholder="例如：提取下一步行动；对比方案差异；改写为新人指南。留空时提炼要点、去除重复并保留分歧。" value={instruction} onChange={event => setInstruction(event.target.value)}/></label><div className="merge-confirm-sources">{selectedMergeItems.map(value => <span key={value.id}>{conclusionTitle(value)}</span>)}</div></div><footer><button className="secondary" disabled={busy} onClick={() => setConfirmingMerge(false)}>返回选择</button><button className="primary" disabled={busy || !mergeReady || !mergeSessionId} onClick={() => void startMerge()}><Sparkles size={14}/>{busy ? '正在准备…' : '生成预处理结果'}</button></footer></section></div>}
  </div>;
}
