import React, { useEffect, useState } from 'react';
import { Upload, Check, LoaderCircle, ArrowLeft, Square, Trash2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { AgentSession, Draft, PreparationScope, Transfer } from '../shared/types';
import { contributionCategoryInfo, titleSubject } from '../shared/content';
import { useAutosave } from './autosave';
const api = window.workbench;
export { contributionStatus as draftStatus } from '../shared/contribution-status';
import { contributionStatus as draftStatus } from '../shared/contribution-status';
import { preparationErrorMessage } from '../shared/preparation-error';
export function DraftEditor({ draft, session, sourceTitle, sourceSession, transfers, run, notice, close, reorganized, returnToList = false, viewShared, viewConclusion }: { draft: Draft; session?: AgentSession; sourceTitle?: string; sourceSession?: AgentSession; transfers: Transfer[]; run: <T>(fn: () => Promise<T>) => Promise<T | undefined>; notice: (s: string) => void; close: () => void; reorganized: (draft: Draft) => void; returnToList?: boolean; viewShared: (projectId: string, path: string) => void; viewConclusion: (projectId: string, id: string) => void }) {
  const [busy, setBusy] = useState(false), [submitted, setSubmitted] = useState(false), [expanded, setExpanded] = useState(false);
  const [leaving, setLeaving] = useState(false);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [choosingScope, setChoosingScope] = useState(false), [reorganizeScope, setReorganizeScope] = useState<PreparationScope>('full');
  const [showRepo, setShowRepo] = useState(!!draft.repoUrlOverride);
  const [renaming, setRenaming] = useState<{ artifactId?: string; title: string }>();
  const [answers, setAnswers] = useState<Record<string, string>>({}), [now, setNow] = useState(Date.now());
  const generating = draft.generation === 'running', ready = draft.generation === 'ready', isMerge = !!draft.mergeSources?.length, isLocalMerge = !!draft.conclusionMergeProjectId;
  const artifacts = draft.artifacts || [], selectedArtifacts = artifacts.filter(item => item.selected);
  const transfer = transfers.find(item => item.id === draft.submitted);
  const uploaded = !!draft.submitted || artifacts.some(item => !!item.submitted), locked = busy || leaving || submitted || uploaded;
  const editor = useAutosave('draft-supplement:' + draft.id, { supplement: draft.supplement || '', repoUrlOverride: draft.repoUrlOverride || '' }, value => api.call('draft.supplement', { id: draft.id, ...value }));
  const mergeEditor = useAutosave('content-merge:' + draft.id + ':' + (draft.generationFinishedAt || 'pending'), { title: draft.title, body: draft.body }, value => api.call('content.merge.save', { id: draft.id, ...value }));
  const value = editor.value, repoUrl = value.repoUrlOverride.trim() || draft.repoUrl || '';
  const change = (patch: Partial<typeof value>) => editor.change({ ...value, ...patch });
  const back = () => void run(async () => {
    setLeaving(true);
    try {
      await (isMerge ? mergeEditor.flush() : editor.flush());
      close();
    } finally { setLeaving(false); }
  });
  const stop = () => void run(async () => {
    setLeaving(true);
    try {
      await api.call('draft.cancel', { id: draft.id });
      await editor.flush();
      notice('已停止整理，现有内容已保留');
      close();
    } finally { setLeaving(false); }
  });
  useEffect(() => { setNow(Date.now()); if (!generating) return; const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [generating, draft.generationStartedAt]);
  useEffect(() => { if (ready) setShowRepo(!!draft.repoUrlOverride); }, [draft.repoUrl, ready]);
  const elapsed = Math.max(0, Math.floor((now - Date.parse(draft.generationStartedAt || draft.createdAt)) / 1000));
  const baselineIndex = sourceSession && draft.snapshot?.lastMessageId ? sourceSession.messages.findIndex(message => message.id === draft.snapshot!.lastMessageId) : -1;
  const baselineWasEmpty = !!draft.snapshot && !draft.snapshot.lastMessageId && (draft.snapshot.totalMessageCount ?? draft.snapshot.messageCount) === 0;
  const incrementalCount = sourceSession ? baselineIndex >= 0 ? sourceSession.messages.length - baselineIndex - 1 : baselineWasEmpty ? sourceSession.messages.length : 0 : 0;
  const hasNewSource = incrementalCount > 0;
  const chooseScope = () => { setReorganizeScope(hasNewSource ? 'incremental' : 'full'); setChoosingScope(true); };
  const backLabel = returnToList ? '返回整理任务列表' : isLocalMerge ? '返回个人结论库' : isMerge ? '返回项目文档' : sourceTitle ? `返回“${sourceTitle}”` : '返回原会话';
  const selectedDestination = draft.destinations?.find(item => item.path === draft.target);
  const destinationLabel = generating ? '识别中…' : ready && draft.target ? selectedDestination?.id === 'default' ? '我的成果（自动选择）' : `${selectedDestination?.description || '项目成果'}（自动选择）` : '尚未确定';
  const visibleBody = draft.body.replace(/^#\s+(.+)\r?\n+/u, (full, heading) => heading.trim() === draft.title.trim() ? '' : full);
  const status = draft.mergeCompletedAt ? isLocalMerge ? '处理结果已保存' : '语义合并已保存' : generating ? session?.approvals.length ? '需要你确认一项操作' : isLocalMerge ? '正在按要求处理…' : isMerge ? '正在进行语义融合…' : '正在整理…' : ready ? isLocalMerge ? '预处理结果已生成，请审阅后保存' : isMerge ? '融合完成，请审阅后确认' : '已整理好，请确认后上传' : draft.generation === 'error' ? isLocalMerge ? '处理失败，可重试' : isMerge ? '语义融合失败，可重试' : '整理失败，可重试' : '已停止，可重新整理';
  return <div className="draft-editor">
    <div className="draft-editor-heading"><button className="text-button draft-back" title={generating ? '返回不会停止整理' : undefined} disabled={leaving} onClick={back}><ArrowLeft size={15}/><span>{leaving ? '正在返回…' : backLabel}</span></button><span className="spacer"/>{generating && <><span className="muted small">返回后仍会继续整理</span><button className="secondary compact" disabled={leaving} onClick={stop}><Square size={12}/>停止整理</button></>}{!uploaded && !submitted && !draft.mergeCompletedAt && <button className="secondary compact danger" disabled={busy || leaving} onClick={() => setConfirmingDelete(true)}><Trash2 size={13}/>删除整理任务</button>}</div>
    <section className="preparation-summary" aria-label="成果整理进度">
      <div className="preparation-status" aria-live="polite" aria-label="整理状态">{generating && <LoaderCircle size={17} className="spin"/>}<strong>{draft.mergeCompletedAt ? status : draft.submitted ? draftStatus(draft, transfer) : status}</strong>{generating && <span className="muted small" aria-label="整理已用时间">{elapsed < 60 ? `${elapsed} 秒` : `${Math.floor(elapsed / 60)} 分 ${elapsed % 60} 秒`}</span>}{!generating && !isMerge && ready && <button className="text-button" disabled={busy || leaving} onClick={chooseScope}>再次整理</button>}{!locked && !generating && !draft.submitted && !draft.mergeCompletedAt && (isMerge || !ready) && <button className="text-button" onClick={() => void run(() => { notice(''); return api.call('draft.retry', { id: draft.id }); })}>{draft.generation === 'error' ? '重试' : isLocalMerge ? '重新处理' : isMerge ? '重新进行语义融合' : '重新整理'}</button>}</div>
      <p className="muted small preparation-source">{isMerge ? `${isLocalMerge ? '处理' : '融合'} ${draft.mergeSources!.length} 条${isLocalMerge ? '本地结论' : '项目文档'}；使用“${sourceTitle || '工作会话'}”完成整理，不会写入原对话` : <>来自“{sourceTitle || '原工作会话'}”{draft.snapshot ? `，${draft.preparationScope === 'incremental' ? `增量整理了 ${draft.snapshot.messageCount} 条新增消息` : '全量整理'}，采用截至 ${new Date(draft.snapshot.capturedAt).toLocaleString()} 的内容` : ''}{hasNewSource ? `；原会话另有 ${incrementalCount} 条新增消息` : ''}</>}</p>
      {draft.generationError && <div className="inline-error" role="alert">{preparationErrorMessage(draft.generationError)}</div>}
      {generating && session?.approvals.map(a => <div className="approval" key={a.id}><strong>{a.title}</strong>{a.summary && <pre className="approval-summary">{a.summary}</pre>}<details><summary>查看请求详情</summary><pre>{a.details}</pre></details>{a.questions?.map(q => <label className="field" key={q.id}>{q.text}{a.method === 'cursor/ask_question' ? <select value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}><option value="">选择答案</option>{q.options.map(o => <option key={o}>{o}</option>)}</select> : <input value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}/>}</label>)}<div className="row">{a.options.map(o => <button key={o.id} className={o.kind === 'deny' ? 'secondary' : 'primary'} onClick={() => void run(() => api.call('session.answer', { id: session.id, requestId: a.id, option: o.id, answers }))}>{o.label}</button>)}</div></div>)}
    </section>

    {isMerge && draft.body && <section className="semantic-merge-review" aria-label={isLocalMerge ? '预处理结果' : '语义合并结果'}><div className="merge-source-list"><b>{isLocalMerge ? '本次处理的结论' : '本次融合来源'}</b>{draft.mergeSources!.map(source => <span key={source.id}>{source.title} · {source.author} · v{source.revision}</span>)}</div>{isLocalMerge && draft.conclusionMergeInstruction && <div className="callout"><div><b>你的处理要求</b><small>{draft.conclusionMergeInstruction}</small></div></div>}<label className="field">{isLocalMerge ? '结果标题' : '合并后标题'}<input aria-label={isLocalMerge ? '结果标题' : '合并后标题'} disabled={locked} value={mergeEditor.value.title} onChange={e => mergeEditor.change({ ...mergeEditor.value, title: e.target.value })}/></label><label className="field">{isLocalMerge ? '预处理结果内容' : '融合后的项目文档'}<textarea aria-label={isLocalMerge ? '预处理结果内容' : '融合后的项目文档'} rows={20} disabled={locked} value={mergeEditor.value.body} onChange={e => mergeEditor.change({ ...mergeEditor.value, body: e.target.value })}/></label>{!locked && mergeEditor.status !== '已保存' && <div className="row small muted" role="status"><span>{mergeEditor.status}</span>{mergeEditor.status.startsWith('保存失败') && <button className="text-button" onClick={mergeEditor.retry}>重试保存</button>}</div>}<details className="merge-safety"><summary>{isLocalMerge ? '保存说明' : '合并保存规则'}</summary><p>确认时会再次核对所有来源版本；任何来源已变化都会停止保存。只有保存成功后原{isLocalMerge ? '结论才会移入历史，系统不会直接删除或覆盖' : '条目才会归档，AI 无权直接删除或覆盖'}。</p></details></section>}
    {isMerge && uploaded && <div className="row"><span>{draft.titleAlias || draft.title}{draft.titleAlias ? '（本地名称）' : ''}</span><button className="text-button" disabled={busy || leaving} onClick={() => setRenaming({ title: draft.titleAlias || titleSubject(draft.title) })}>修改名称</button></div>}
    {!isMerge && artifacts.length > 0 ? <section className="artifact-results" aria-label="整理结果">
      <p className="muted small">AI 已按用途拆成 {artifacts.length} 项。取消不需要共享的项目后再上传。</p>
      {artifacts.map(item => {
        const itemTransfer = transfers.find(transfer => transfer.id === item.submitted);
        const itemRepo = value.repoUrlOverride.trim() || item.repoUrl || '';
        return <article className={'contribution-result artifact-result ' + (item.selected ? '' : 'artifact-unselected')} key={item.id}>
          <header><label className="check-row"><input type="checkbox" aria-label={`选择成果：${item.titleAlias || item.title}`} checked={item.selected} disabled={locked} onChange={e => void run(() => api.call('draft.artifactSelection', { id: draft.id, artifactId: item.id, selected: e.target.checked }))}/><span><b>{item.titleAlias || item.title}</b><small>{contributionCategoryInfo[item.category].label}{item.titleAlias ? ' · 本地名称' : ''}</small></span></label><button className="text-button" disabled={!ready || busy || leaving} onClick={() => setRenaming({ artifactId: item.id, title: item.titleAlias || titleSubject(item.title) })}>修改名称</button>{itemTransfer && <span className={'badge ' + itemTransfer.status}>{({ queued: '等待上传', running: '上传中', done: '上传成功', error: '上传失败' })[itemTransfer.status]}</span>}</header>
          {itemRepo && <p className="repository-reference">相关仓库：<a href={itemRepo} onClick={e => { e.preventDefault(); void run(() => api.call('open.link', itemRepo)); }}>{itemRepo}</a></p>}
          <div className={'generated-preview markdown ' + (!expanded && item.body.length > 800 ? 'collapsed' : '')}><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.body}</ReactMarkdown></div>
          {item.body.length > 800 && <button className="text-button" onClick={() => setExpanded(!expanded)}>{expanded ? '收起详情' : '展开详情'}</button>}
          <p className="artifact-destination">保存到：{contributionCategoryInfo[item.category].label}</p>
          {itemTransfer?.status === 'error' && <div className="inline-error" role="alert">上传失败：{itemTransfer.error}<button className="secondary compact" onClick={() => void run(() => api.call('transfer.retry', { id: itemTransfer.id }))}>重试</button></div>}{itemTransfer?.status === 'done' && <button className="secondary compact" onClick={() => viewShared(itemTransfer.binding.project.id, itemTransfer.target)}>查看上传结果</button>}
        </article>;
      })}
    </section> : !isMerge && draft.body && <section className="contribution-result" aria-label="整理结果">
      {!ready && !draft.submitted && <p className="muted small">以下是上次整理的内容</p>}
      <div className="row"><h2>{draft.titleAlias || draft.title}</h2><button className="text-button" disabled={!ready || busy || leaving} onClick={() => setRenaming({ title: draft.titleAlias || titleSubject(draft.title) })}>修改名称</button></div>
      {repoUrl && <p className="repository-reference">相关仓库：<a href={repoUrl} onClick={e => { e.preventDefault(); void run(() => api.call('open.link', repoUrl)); }}>{repoUrl}</a></p>}
      <div className={'generated-preview markdown ' + (!expanded && visibleBody.length > 800 ? 'collapsed' : '')} aria-label="整理说明"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ href, children }) => <a href={href} onClick={e => { e.preventDefault(); if (href && /^https?:/.test(href)) void run(() => api.call('open.link', href)); }}>{children}</a>, img: ({ alt }) => <span>[图片：{alt || '附件'}]</span> }}>{visibleBody}</ReactMarkdown></div>
      {visibleBody.length > 800 && <button className="text-button" onClick={() => setExpanded(!expanded)}>{expanded ? '收起详情' : '展开详情'}</button>}
    </section>}
    {!isMerge && (ready || draft.body) && !locked && <details className="repository-correction" open={showRepo} onToggle={e => setShowRepo(e.currentTarget.open)}><summary>仓库与代码版本（可选）</summary><label className="field">相关 GitHub 仓库<input aria-label="GitHub 仓库链接" placeholder={draft.repoUrl || 'https://github.com/owner/repository'} value={value.repoUrlOverride} onChange={e => change({ repoUrlOverride: e.target.value })}/></label>{draft.git && <><label className="check-row"><input type="checkbox" aria-label="记录当前代码版本" checked={!!draft.includeGit} onChange={e => void run(() => api.call('draft.git', { id: draft.id, include: e.target.checked }))}/>记录当前代码版本（不会上传代码）</label><p className="muted small git-version">{draft.git.branch} · {draft.git.commit?.slice(0, 12) || '无提交'} · {draft.git.dirty ? '有未提交改动' : '无未提交改动'}</p></>}</details>}
    {!isMerge && !artifacts.length && transfer?.status === 'error' && <div className="inline-error" role="alert">上传失败：{transfer.error}<div className="row"><button className="secondary" onClick={() => void run(() => api.call('transfer.retry', { id: transfer.id }))}>重试原上传</button><button className="secondary" onClick={() => void run(async () => { await api.call('draft.revise', { id: draft.id }); notice('修订草稿已创建，可在上方草稿列表选择并补充后上传'); })}>生成修订草稿</button></div></div>}
    {!isMerge && <label className="field contribution-supplement">给团队的补充（可选）<textarea rows={3} aria-label="给团队的补充（可选）" placeholder="只有需要补充或更正时填写" disabled={locked} value={value.supplement} onChange={e => change({ supplement: e.target.value })}/></label>}
    {!isMerge && !locked && editor.status !== '已保存' && <div className="row small muted" role="status"><span>{editor.status}</span>{editor.status.startsWith('保存失败') && <button className="text-button" onClick={editor.retry}>重试保存</button>}</div>}
    {!isMerge && !artifacts.length && <div className="upload-destination" aria-label="上传位置" title={ready ? draft.target : undefined}><span>上传位置</span>{draft.binding ? <b>{draft.binding.project.name} / {destinationLabel}</b> : <b>未绑定项目，无法上传</b>}</div>}
    {isMerge ? <div className="draft-actions"><button className="secondary back-action" disabled={leaving} onClick={back}>{backLabel}</button><span className="spacer"/>{draft.mergeCompletedAt && draft.mergeResultId && isLocalMerge ? <button className="primary" onClick={() => viewConclusion(draft.conclusionMergeProjectId!, draft.mergeResultId!)}>查看处理结果</button> : draft.mergeCompletedAt && draft.mergeProjectId && draft.mergeResultPath ? <button className="primary" onClick={() => viewShared(draft.mergeProjectId!, draft.mergeResultPath!)}>查看合并结果</button> : <button className="primary" disabled={busy || leaving || !ready || !mergeEditor.value.title.trim() || !mergeEditor.value.body.trim()} onClick={() => void run(async () => { setBusy(true); try { await mergeEditor.flush(); if (isLocalMerge) { const result = await api.call<{ id: string }>('conclusion.merge.commit', { id: draft.id }); setSubmitted(true); notice('新结论已保存，原结论已移入历史'); viewConclusion(draft.conclusionMergeProjectId!, result.id); } else { const result = await api.call<{ path: string }>('content.merge.commit', { id: draft.id }); setSubmitted(true); notice('语义合并已保存，原条目已归档'); viewShared(draft.mergeProjectId!, result.path); } } finally { setBusy(false); } })}><Check size={15}/>{busy ? '正在核对并保存…' : isLocalMerge ? `保存新结论并将 ${draft.mergeSources!.length} 条原结论移入历史` : `确认合并并归档 ${draft.mergeSources!.length} 条原文`}</button>}</div> : <div className="draft-actions">{!draft.submitted && !submitted ? <>{draft.body && <button className="secondary back-action" disabled={leaving} onClick={back}>{backLabel}</button>}<span className="spacer"/><button className="primary" disabled={busy || leaving || !ready || !(artifacts.length ? selectedArtifacts.length : draft.body.trim()) || !draft.binding} onClick={() => void run(async () => { setBusy(true); try { await editor.flush(); await api.call('draft.submit', { id: draft.id }); setSubmitted(true); notice(artifacts.length ? `已开始上传 ${selectedArtifacts.length} 项成果；所选成果也已整理到本地结论` : '已开始上传成果；同时已整理到本地结论'); } finally { setBusy(false); } })}><Upload size={15}/>{busy ? '正在上传…' : artifacts.length ? `确认上传 ${selectedArtifacts.length} 项` : '确认上传'}</button></> : <><button className="secondary back-action" onClick={back}>{backLabel}</button><span className="green row"><Check size={17}/>{transfers.some(item => item.status === 'error') ? '部分上传失败，可在对应成果中重试' : transfers.length && transfers.every(item => item.status === 'done') ? '上传已完成。点击上方成果中的“查看上传结果”，即可打开团队公共区里的内容。' : '正在上传'}</span>{!artifacts.length && transfer?.status === 'done' && <button className="primary compact" onClick={() => viewShared(transfer.binding.project.id, transfer.target)}>查看上传结果</button>}</>}</div>}
    {renaming && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="rename-result-title"><header><h2 id="rename-result-title">修改成果名称</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setRenaming(undefined)}>×</button></header><div className="modal-body"><label className="field">成果名称<input autoFocus aria-label="成果名称" maxLength={120} value={renaming.title} onChange={e => setRenaming({ ...renaming, title: e.target.value })}/></label><p className="muted small">{uploaded ? '只修改本机显示名称，已上传的成果包和共享区标题保持不变。' : '修改后将使用新名称上传，内容和勾选状态保持不变。'}</p></div><footer><button className="secondary" disabled={busy} onClick={() => setRenaming(undefined)}>取消</button><button className="primary" disabled={busy || !renaming.title.trim()} onClick={() => void run(async () => { setBusy(true); try { await api.call('draft.renameResult', { id: draft.id, artifactId: renaming.artifactId, title: renaming.title }); setRenaming(undefined); notice(uploaded ? '本地名称已保存，远端未修改' : '成果名称已保存'); } finally { setBusy(false); } })}>保存名称</button></footer></section></div>}
    {confirmingDelete && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-draft-title"><header><h2 id="delete-draft-title">确认删除整理任务</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setConfirmingDelete(false)}>×</button></header><div className="modal-body"><p>将删除本机整理任务“{draft.title}”及其临时文件{generating ? '，并停止正在运行的整理' : ''}。</p><p className="muted small">已经上传或保存到公共区的成果不会被删除；如需删除公共成果，请到“公共成果”或“整理项目文档”中单独操作。</p></div><footer><button className="secondary" disabled={busy} onClick={() => setConfirmingDelete(false)}>取消</button><button className="primary danger" disabled={busy} onClick={() => void run(async () => { setBusy(true); try { await api.call('draft.delete', { id: draft.id }); notice('本机整理任务已删除，远端成果未受影响'); close(); } finally { setBusy(false); } })}>{busy ? '正在删除…' : '确认删除整理任务'}</button></footer></section></div>}
    {choosingScope && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="reorganize-scope-title"><header><h2 id="reorganize-scope-title">选择整理范围</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={() => setChoosingScope(false)}>×</button></header><div className="modal-body"><p className="muted small">会新建一条整理任务，当前任务及已上传内容保持不变。</p><div className="preparation-options"><label className="preparation-option"><input type="radio" name="reorganize-scope" aria-label="增量整理" checked={reorganizeScope === 'incremental'} disabled={busy || !hasNewSource} onChange={() => setReorganizeScope('incremental')}/><span><b>增量整理</b><small>{hasNewSource ? `只整理上次快照后新增的 ${incrementalCount} 条消息；阶段摘要和参考资料仅作上下文。` : '上次整理后没有新增消息，暂时不能使用。'}</small></span></label><label className="preparation-option"><input type="radio" name="reorganize-scope" aria-label="全量整理" checked={reorganizeScope === 'full'} disabled={busy} onChange={() => setReorganizeScope('full')}/><span><b>全量整理</b><small>重新读取当前 Session 截至现在的全部消息、阶段摘要和参考资料。</small></span></label></div></div><footer><button className="secondary" disabled={busy} onClick={() => setChoosingScope(false)}>取消</button><button className="primary" disabled={busy || (reorganizeScope === 'incremental' && !hasNewSource)} onClick={() => void run(async () => { setBusy(true); try { if (!uploaded) await editor.flush(); const next = await api.call<Draft>('draft.reorganize', { id: draft.id, scope: reorganizeScope }); setChoosingScope(false); notice(`已创建${reorganizeScope === 'incremental' ? '增量' : '全量'}整理任务，原任务已保留`); reorganized(next); } finally { setBusy(false); } })}>{busy ? '正在创建…' : `开始${reorganizeScope === 'incremental' ? '增量' : '全量'}整理`}</button></footer></section></div>}
  </div>;
}
