import type { SourceFile } from '../shared/types';
import { SharedContentLibrary } from './shared-content';
import { ProjectBriefEditor } from './project-brief-editor';
import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Folder, FolderOpen, FileText, Plus, Settings as SettingsIcon, ArrowUp, ArrowLeft, RefreshCw, Upload, Download, Link, X, Check, ChevronRight, MessageSquare, Layers, Server, Unplug, Search, Paperclip, Square, ShieldCheck, FileArchive, HardDrive, PanelRightClose, Activity, Sparkles, ExternalLink, Copy, Terminal, CircleHelp } from 'lucide-react';
import type { AgentSession, ConnectionProfile, Draft, FilePreview, Project, Provider, RemoteEntry, Settings, Snapshot, WorkspaceAccess } from '../shared/types';
import './styles.css';
import { DraftEditor, draftStatus } from './draft-editor';
import { ModelPicker } from './model-picker';
import { PermissionPicker } from './permissions';
import { ComposerSettings } from './composer-settings';
import type { PermissionMode } from '../shared/types';
import { useAutosave } from './autosave';
import type { SessionInput } from '../shared/types';
import { ProviderAuthPanel, canUseProvider } from './provider-auth';
import { ProjectOnboarding } from './project-onboarding';
import { projectSetupIdentity } from '../shared/project-brief';
const api = window.workbench;
const bytes = (n: number) => n < 1024 ? n + ' B' : n < 1024 ** 2 ? (n / 1024).toFixed(1) + ' KB' : (n / 1024 ** 2).toFixed(1) + ' MB';
const providerLabel = (p: Provider) => p === 'codex' ? 'Codex · GPT' : 'Cursor';
const statusLabels = { idle: '就绪', starting: '连接 CLI', running: '处理中', approval: '等待操作确认', error: '需要处理' };
function Markdown({ text }: { text: string }) { return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ href, children }) => <a href={href} onClick={e => { e.preventDefault(); if (href && /^https?:/.test(href)) void api.call('open.link', href); }}>{children}<ExternalLink size={11} /></a>, img: ({ alt }) => <span>[图片：{alt || '附件'}]</span> }}>{text}</ReactMarkdown></div>; }
function Modal({ title, children, close, wide = false }: { title: string; children: React.ReactNode; close: () => void; wide?: boolean }) { return <div className="modal-backdrop"><section className={'modal ' + (wide ? 'wide' : '')}><header><h2>{title}</h2><button className="icon" aria-label="关闭窗口" onClick={close}><X size={19}/></button></header>{children}</section></div>; }
function App() {
  const [state, setState] = useState<Snapshot>(); const [notice, setNotice] = useState('');
  const [view, setView] = useState<'sessions' | 'drafts' | 'transfers' | 'library'>('sessions'); const [sessionId, setSessionId] = useState('');
  const [projectId, setProjectId] = useState(''); const [remoteDir, setRemoteDir] = useState(''); const [entries, setEntries] = useState<RemoteEntry[]>([]); const [fileError, setFileError] = useState(''); const [loadingFiles, setLoadingFiles] = useState(false);
  const [preview, setPreview] = useState<FilePreview>(); const [previewOrigin, setPreviewOrigin] = useState(''); const [search, setSearch] = useState('');
  const [settingsOpen, setSettingsOpen] = useState(false); const [connectOpen, setConnectOpen] = useState(false); const [newOpen, setNewOpen] = useState(false);
  const [busy, setBusy] = useState(false); const [inputVersion, updateInputs] = useState(0); const localInputs = useRef<Record<string, SessionInput>>({}); const [sendingIds, setSendingIds] = useState<string[]>([]); const [inputError, setInputError] = useState('');
  const [handoff, setHandoff] = useState<{ id: string; text: string }>(); const [history, setHistory] = useState<{ id: string; text: string }>();
  const [draftId, setDraftId] = useState('');
  const [showClosed, setShowClosed] = useState(false), [closingSession, setClosingSession] = useState<AgentSession>();
  const [briefOpen, setBriefOpen] = useState(false);
  const [projectCreateOpen, setProjectCreateOpen] = useState(false), [createGroup, setCreateGroup] = useState('');
  const [onboarding, setOnboarding] = useState<{ groupName: string; contextKey: string }>(); const autoPrompted = useRef(false);
  const [groupsError, setGroupsError] = useState(''), [groupsBusy, setGroupsBusy] = useState(false); const groupsLoading = useRef(false);
  const fileRequest = useRef(0), previewRequest = useRef(0), scroller = useRef<HTMLDivElement>(null); const snapshotSequence = useRef(0);
  const refresh = async () => { const n = ++snapshotSequence.current; const next = await api.call<Snapshot>('snapshot'); if (n === snapshotSequence.current) setState(next); };
  const run = async <T,>(fn: () => Promise<T>): Promise<T | undefined> => { try { return await fn(); } catch (e: any) { setNotice(e.message); return undefined; } };
  useEffect(() => { void api.call<Snapshot>('snapshot').then(next => { setState(next); setConnectOpen(!next.workspaceReady); }); return api.subscribe(event => { if (event.type === 'state') void refresh(); else setNotice(event.message); }); }, []);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 15000); return () => clearTimeout(timer); }, [notice]);
  const connection = state?.connection, projects = connection?.connected ? connection.profile.projects : state?.settings.offlineAuthorization?.profile.projects || [], project = projects.find(p => p.id === projectId);
  const workspaces = connection?.connected ? connection.workspaces || [] : state?.settings.offlineAuthorization?.workspaces || [];
  const creatableGroups = connection?.connected ? workspaces.filter(w => w.canCreateProject && !w.accessError) : [];
  const readOnly = state?.accessMode === 'readonly';
  const projectAdmin = !!workspaces.find(w => w.groupName === project?.groupName)?.canCreateProject;
  const openCreate = (groupName = '') => {
    const workspace = creatableGroups.find(w => w.groupName === groupName);
    if (workspace?.isEmpty && connection?.connected) { autoPrompted.current = true; setOnboarding({ groupName, contextKey: projectSetupIdentity(connection.profile, groupName) }); }
    else { setCreateGroup(groupName); setProjectCreateOpen(true); }
  };
  const onboardingWorkspace = workspaces.find(w => w.groupName === onboarding?.groupName && connection && projectSetupIdentity(connection.profile, w.groupName!) === onboarding?.contextKey);
  useEffect(() => { autoPrompted.current = false; setOnboarding(undefined); }, [connection?.connected, connection?.profile.id, connection?.profile.username, connection?.profile.fingerprint, connection?.profile.host, connection?.profile.port, connection?.profile.localRoot]);
  useEffect(() => {
    if (!state?.workspaceReady || !connection?.connected || connectOpen || settingsOpen || newOpen || projectCreateOpen || onboarding || handoff || history || autoPrompted.current) return;
    const first = creatableGroups.find(w => w.isEmpty);
    if (first?.groupName) { autoPrompted.current = true; setOnboarding({ groupName: first.groupName, contextKey: projectSetupIdentity(connection.profile, first.groupName) }); }
  }, [state?.workspaceReady, connection?.connected, connectOpen, settingsOpen, newOpen, projectCreateOpen, onboarding, handoff, history, JSON.stringify(creatableGroups)]);
  const session = state?.sessions.find(s => s.id === sessionId), draft = state?.drafts.find(d => d.id === draftId);
  const workSessions = state?.sessions.filter(s => s.purpose === 'work' && s.binding?.project.groupName === project?.groupName) || [];
  const preparingCount = state?.drafts.filter(d => !d.submitted && d.generation === 'running').length || 0;
  const readyCount = state?.drafts.filter(d => !d.submitted && d.generation === 'ready').length || 0;
  const sessionDraft = state?.drafts.find(d => d.sessionId === sessionId && !d.submitted);
  const visibleSessions = workSessions.filter(s => showClosed ? !!s.closedAt : !s.closedAt);
  const waitingSessions = state?.sessions.filter(s => s.approvals.length > 0 && !s.closedAt) || [];
  useEffect(() => { if (!visibleSessions.some(s => s.id === sessionId)) setSessionId(visibleSessions[0]?.id || ''); }, [JSON.stringify(visibleSessions.map(s => s.id))]);
  const currentInput = localInputs.current[sessionId] || state?.inputs[sessionId] || { text: '', sourceIds: [], answers: {} };
  const composer = currentInput.text, selectedSources = currentInput.sourceIds, answers = currentInput.answers;
  const editInput = (id: string, patch: Partial<SessionInput>) => {
    const value = { ...(localInputs.current[id] || state?.inputs[id] || { text: '', sourceIds: [], answers: {} }), ...patch };
    localInputs.current[id] = value; updateInputs(n => n + 1);
    void api.call('session.input', { id, input: value }).then(() => setInputError(''), (e: Error) => setInputError('输入保存失败，请保留当前窗口并重试：' + e.message));
  };
  const setComposer = (text: string) => editInput(sessionId, { text });
  const setSelectedSources = (sourceIds: string[]) => editInput(sessionId, { sourceIds });
  const setAnswers = (answers: Record<string, string>) => editInput(sessionId, { answers });
  useEffect(() => { if (!projects.some(p => p.id === projectId)) setProjectId(projects[0]?.id || ''); }, [connection?.connected, JSON.stringify(projects)]);
  useEffect(() => { setPreview(undefined); previewRequest.current++; setRemoteDir(project?.remoteRoot || ''); }, [projectId, connection?.profile.id, connection?.profile.username]);
  const loadGroups = async () => {
    if (groupsLoading.current || !connection?.connected) return;
    groupsLoading.current = true; setGroupsBusy(true);
    try { await api.call('remote.manifest'); setGroupsError(''); }
    catch (e: any) { setGroupsError(e.message); }
    finally { groupsLoading.current = false; setGroupsBusy(false); }
  };
  useEffect(() => { const timer = setInterval(() => { if (document.visibilityState === 'visible') void loadGroups(); }, 30000); return () => clearInterval(timer); }, [connection?.connected, connection?.profile.id, connection?.profile.username]);
  useEffect(() => setGroupsError(''), [connection?.profile.id, connection?.profile.username, connection?.connected]);
  const loadFiles = async () => {
    const n = ++fileRequest.current; if (!state?.workspaceReady || !project || !remoteDir) { setEntries([]); setFileError(''); setLoadingFiles(false); return; }
    setLoadingFiles(true); setFileError('');
    try { const items = await api.call<RemoteEntry[]>('remote.list', { projectId: project.id, path: remoteDir }); if (fileRequest.current === n) setEntries(items); }
    catch (e: any) { if (fileRequest.current === n) { setFileError(e.message); setEntries([]); } }
    finally { if (fileRequest.current === n) setLoadingFiles(false); }
  };
  useEffect(() => { void loadFiles(); return () => { fileRequest.current++; }; }, [remoteDir, projectId, connection?.connected, state?.workspaceReady]);
  useEffect(() => { const timer = setInterval(() => { if (document.visibilityState === 'visible' && connection?.connected) void loadFiles(); }, 30000); return () => clearInterval(timer); }, [remoteDir, projectId, connection?.connected, state?.workspaceReady]);
  useEffect(() => { if (scroller.current) scroller.current.scrollTop = scroller.current.scrollHeight; }, [sessionId, session?.approvals.length, session?.messages.length, session?.messages.at(-1)?.text]);
  const selectSession = (s: AgentSession) => { setSessionId(s.id); setView('sessions'); if (s.binding && projects.some(p => p.id === s.binding!.project.id)) setProjectId(s.binding.project.id); };
  const send = async () => {
    if (!session || session.closedAt || !composer.trim() || sendingIds.includes(session.id) || ['starting', 'running', 'approval'].includes(session.status)) return;
    const id = session.id, sent = { ...currentInput }; setSendingIds(ids => [...ids, id]);
    const result = await run(() => api.call('session.send', { id, text: sent.text, sourceIds: sent.sourceIds }));
    // Bind the acknowledgement to the original session, and preserve edits typed while waiting.
    const latest = localInputs.current[id] || state?.inputs[id] || sent;
    if (result && latest.text === sent.text && JSON.stringify(latest.sourceIds) === JSON.stringify(sent.sourceIds)) editInput(id, { text: '', sourceIds: [] });
    setSendingIds(ids => ids.filter(x => x !== id));
  };
  const openFile = async (item: RemoteEntry) => {
    if (item.kind === 'directory') { setRemoteDir(item.path); return; }
    if (item.kind === 'link') { setNotice('第一版不直接打开符号链接，请管理员提供实际目录或文件入口'); return; }
    const n = ++previewRequest.current; const selectedProject = projectId;
    const result = await run(() => api.call<FilePreview>('remote.preview', { projectId: selectedProject, path: item.path }));
    if (result && n === previewRequest.current) { setPreview(result); setPreviewOrigin(selectedProject); }
  };
  if (!state) return <div className="boot"><Layers size={34}/><p>正在启动团队工作台…</p></div>;
  if (!state.workspaceReady) return <div className="setup-gate"><div className="setup-card"><div className="welcome-symbol"><FolderOpen size={30}/></div><span className="eyebrow">WORKSPACE SETUP</span><h1>{connection?.connected ? '还没有加入工作组' : '先连接团队账号'}</h1>{connection?.connected && <p>请联系管理员分配工作组。</p>}{connection?.connected && <button className="secondary" onClick={() => void run(() => api.call('remote.manifest'))}>刷新工作组</button>}<button className="primary large" onClick={() => setConnectOpen(true)}>配置账号与本机目录</button></div>{connectOpen && <ConnectModal settings={state.settings} connection={connection} close={() => setConnectOpen(false)} run={run} onConnected={() => { setConnectOpen(false); void refresh(); }}/> }</div>;
  return <div className="app">
    <nav className="rail"><div className="brand-mark"><Layers size={25}/></div><button className={view === 'sessions' ? 'active' : ''} title="工作会话" onClick={() => setView('sessions')}><MessageSquare size={22}/></button><button className={view === 'drafts' ? 'active' : ''} title="整理成果" aria-label="成果草稿" onClick={() => { setView('drafts'); if (!state.drafts.some(d => d.id === draftId)) setDraftId(state.drafts[0]?.id || ''); }}><FileArchive size={22}/>{(preparingCount > 0 || readyCount > 0) && <span className="preparation-nav-badge" aria-label="成果提醒">{preparingCount ? "整理中" : "待确认"}</span>}</button><button className={view === 'transfers' ? 'active' : ''} title="传输记录" onClick={() => setView('transfers')}><Activity size={22}/></button><button title="公共成果" disabled={!project || !connection?.connected} className={view === 'library' ? 'active' : ''} onClick={() => setView('library')}><Search size={22}/></button><div className="rail-spacer"/><button title="设置" onClick={() => setSettingsOpen(true)}><SettingsIcon size={22}/></button><span className="avatar">我</span></nav>
    <div className="shell"><header className="topbar"><div><strong>团队工作台 <span className="version">用户版</span></strong></div><div className="topbar-actions"><button className={'connection-button ' + (connection?.connected ? 'online' : '')} onClick={() => setConnectOpen(true)}><span className="dot"/>{connection?.connected ? `${connection.profile.mode === 'local' ? '本地模拟 · ' : ''}${connection.profile.name} · ${connection.profile.username}` : '连接共享空间'}<ChevronRight size={14}/></button></div></header>
    <div className="body"><aside className="sidebar"><div className="sidebar-head"><h3>我的工作组</h3><div className="row"><button className="icon" title="刷新工作组与项目" disabled={!connection?.connected || groupsBusy} onClick={() => void loadGroups()}><RefreshCw size={15} className={groupsBusy ? 'spin' : ''}/></button><button className="icon" title="刷新文件" disabled={!project} onClick={() => void loadFiles()}><FolderOpen size={15}/></button></div></div>
      {groupsError && <div className="inline-error" role="alert">{groupsError}</div>}
      <div className="workgroup-list" aria-label="按工作组展示项目">{workspaces.map(w => <section className="workgroup" key={w.groupName} data-group-name={w.groupName}><div className="workgroup-title"><b>{w.groupLabel || w.groupName}</b>{w.canCreateProject && <span className="badge">子管理员</span>}<span className="spacer"/>{w.canCreateProject && <button className="icon" title={'在 ' + (w.groupLabel || w.groupName) + ' 创建项目'} onClick={() => openCreate(w.groupName)}><Plus size={15}/></button>}</div>{w.accessError ? <p className="inline-error">{w.accessError}</p> : projects.filter(p => p.groupName === w.groupName).length ? projects.filter(p => p.groupName === w.groupName).map(p => <button className={'workgroup-project ' + (p.id === projectId ? 'selected' : '')} data-project-id={p.id} key={p.id} onClick={() => setProjectId(p.id)}><Folder size={15}/><span>{p.name}</span>{p.id === projectId && <Check size={13}/>}</button>) : <div><p className="muted small">暂无项目{w.canCreateProject ? '，点击 + 创建' : '，等待子管理员创建'}</p>{w.canCreateProject && w.isEmpty && <button className="text-button" onClick={() => openCreate(w.groupName)}>完善项目资料</button>}</div>}</section>)}</div>
      {project ? <><div className="row pad"><button className="text-button" disabled={!connection?.connected} onClick={() => setBriefOpen(true)}>项目资料{project.briefRevision ? ` · v${project.briefRevision}` : ' · 待完善'}</button><button className="text-button" disabled={!connection?.connected} onClick={() => setView('library')}>公共成果</button></div><div className="path-row"><button className="icon" title="上一级" disabled={remoteDir === project.remoteRoot} onClick={() => setRemoteDir(remoteDir.slice(0, remoteDir.lastIndexOf('/')) || project.remoteRoot)}><ArrowLeft size={14}/></button><span title={remoteDir}>{remoteDir.replace(project.remoteRoot, '') || '/'}</span><button className="icon" title="上传文件到当前目录" onClick={() => void run(async () => { await api.call('remote.upload', { projectId, folder: remoteDir }); setNotice('文件已加入上传队列'); setView('transfers'); })}><Upload size={15}/></button></div><label className="search"><Search size={14}/><input placeholder="筛选当前目录" value={search} onChange={e => setSearch(e.target.value)}/></label><div className="file-list">{fileError && <div className="inline-error">{fileError}</div>}{!loadingFiles && !entries.length && !fileError && <div className="muted small pad">此目录还没有文件</div>}{entries.filter(f => f.name.toLowerCase().includes(search.toLowerCase())).map(f => <button key={f.path} className={'file-row ' + (preview?.path === f.path ? 'selected' : '')} onClick={() => void openFile(f)} title={f.path}>{f.kind === 'directory' ? <Folder size={17}/> : <FileText size={17}/>}<span>{f.name}</span>{f.kind === 'directory' ? <ChevronRight size={13}/> : <small>{bytes(f.size)}</small>}</button>)}</div></> : <div className="remote-empty"><Server size={29}/><p>{connection?.connected ? groupsError ? '工作组信息读取失败' : workspaces.length ? '选择工作组下的项目' : '还没有加入工作组' : '连接后自动显示工作组'}</p>{connection?.connected && !groupsError && !workspaces.length && <span>请联系管理员将此账号加入工作组。<br/>加入后点击上方刷新即可。</span>}{connection?.connected && creatableGroups.length > 0 && !projects.length && <button className="primary" onClick={() => openCreate(creatableGroups.length === 1 ? creatableGroups[0].groupName : '')}>创建第一个项目</button>}{!connection?.connected && <button className="secondary" onClick={() => setConnectOpen(true)}>连接团队账号</button>}</div>}
      <div className="session-heading"><h3>本地会话</h3><button className="icon" title="新建会话" disabled={readOnly || !project} onClick={() => setNewOpen(true)}><Plus size={18}/></button></div><div className="session-list">{visibleSessions.map(s => <button className={'session-row ' + (sessionId === s.id && view === 'sessions' ? 'selected' : '')} key={s.id} data-session-id={s.id} onClick={() => selectSession(s)}><span className={'provider-icon ' + s.provider}>{s.provider === 'codex' ? 'G' : 'C'}</span><span><b>{s.title}</b><small>{s.binding ? [s.binding.project.groupLabel, s.binding.project.name].filter(Boolean).join(' / ') : '本地工作'} · {s.closedAt ? '已关闭' : providerLabel(s.provider)}</small></span>{['running', 'starting'].includes(s.status) && <span className="status-pulse"/>}{s.status === 'approval' && <CircleHelp size={15}/>}</button>)}{!visibleSessions.length && <p className="muted small pad">{showClosed ? '没有已关闭的会话。' : '没有打开的会话。'}</p>}</div><button className="closed-toggle text-button" onClick={() => setShowClosed(!showClosed)}>{showClosed ? '返回打开的会话' : `已关闭会话（${workSessions.filter(s => s.closedAt).length}）`}</button>
    </aside>
    <main className="main-content">
    {!connection?.connected && <div className="callout connection-status" role="status"><div><b>{readOnly ? '离线授权已过期 · 只读' : '离线工作'}</b><small>{readOnly ? '已有记录可查看；重新登录后可以继续工作。' : `当前授权有效至 ${new Date(state.offlineExpiresAt || '').toLocaleString()}。共享读写需连接服务器。`}</small></div><button className="secondary" onClick={() => setConnectOpen(true)}>连接团队账号</button></div>}
    {view === 'library' && project && <SharedContentLibrary key={project.id} project={project} username={connection?.profile.username || ''} admin={projectAdmin} notice={setNotice} attach={session?.binding?.project.id === project.id ? async item => { const source = await api.call<SourceFile>('session.attachContent', { id: session.id, contentId: item.id }); editInput(session.id, { sourceIds: [...(localInputs.current[session.id]?.sourceIds || selectedSources), source.id] }); setNotice('已加入当前会话参考资料'); } : undefined}/>}

    {waitingSessions.length > 0 && <div className="pending-approvals" role="status" aria-label="待授权提醒"><ShieldCheck size={17}/><b>{waitingSessions.reduce((n, s) => n + s.approvals.length, 0)} 项操作等待你的授权</b>{waitingSessions.map(s => <button className="secondary compact" key={s.id} onClick={() => { if (s.purpose === 'prepare') { const d = state.drafts.find(d => d.prepareSessionId === s.id); if (d) { setDraftId(d.id); setView('drafts'); } } else selectSession(s); }}>{s.purpose === 'prepare' ? '成果整理' : s.title} · 查看授权</button>)}</div>}
    {view === 'sessions' && (session ? <><div className="session-toolbar"><div><h2>{session.title}</h2><span className="muted small" title={session.cwd}>{providerLabel(session.provider)} <span className="separator">/</span> {session.binding ? [session.binding.project.groupLabel, session.binding.project.name].filter(Boolean).join(' / ') : '本地会话'} <span className="separator">/</span> {session.closedAt ? '已关闭' : statusLabels[session.status]}</span></div><div className="row"><details className="session-materials" key={session.id}><summary>会话资料{session.binding && (projects.find(p => p.id === session.binding!.project.id)?.briefRevision || 0) > (session.projectBrief?.revision || 0) && <span className="materials-update">有更新</span>}</summary><div className="session-materials-content">{session.binding && <div className="row pad muted small"><span>项目资料：{session.projectBrief ? `已引用 v${session.projectBrief.revision}` : '尚未引用'}{(projects.find(p => p.id === session.binding!.project.id)?.briefRevision || 0) > (session.projectBrief?.revision || 0) ? ' · 有新版本可采用' : ''}</span><button className="text-button" disabled={!connection?.connected || ['running', 'starting', 'approval'].includes(session.status)} onClick={() => void run(() => api.call('session.projectContext', { id: session.id }))}>采用当前项目资料</button></div>}<button className="secondary compact" onClick={() => void run(async () => setHandoff({ id: session.id, text: await api.call<string>('handoff.read', { id: session.id }) }))}><FileText size={14}/>查看 Agent 工作记录</button></div></details><button className="secondary compact" onClick={() => void run(async () => setHistory({ id: session.id, text: await api.call<string>('session.history', { id: session.id }) }))}><Upload size={14}/>轨迹上传</button>{session.closedAt ? <button className="secondary compact" onClick={() => void run(async () => { await api.call('session.reopen', { id: session.id }); setShowClosed(false); })}>重新打开会话</button> : <button className="secondary compact" onClick={() => { if (['running', 'starting', 'approval'].includes(session.status)) setClosingSession(session); else void run(() => api.call('session.close', { id: session.id })); }}><X size={14}/>关闭会话</button>}<button aria-label="整理成果" className="primary compact" disabled={readOnly || session.purpose === 'prepare' || busy} onClick={() => void run(async () => { setBusy(true); try { const d = await api.call<Draft>('draft.prepare', { id: session.id }); setDraftId(d.id); setView('drafts'); await refresh(); } finally { setBusy(false); } })}><Sparkles size={14}/>整理成果{sessionDraft && <span className="session-draft-status">{draftStatus(sessionDraft, state.transfers.find(t => t.id === sessionDraft.submitted))}</span>}</button></div></div>
      <div className="messages" ref={scroller}>{!session.messages.length && <div className="session-welcome"><div className="welcome-symbol"><MessageSquare size={26}/></div><h2>开始这次工作</h2><code>{session.cwd}</code></div>}{session.messages.map(m => <article key={m.id} className={'message ' + m.role}><div className="message-author"><span className={'provider-icon ' + (m.role === 'user' ? 'user' : session.provider)}>{m.role === 'user' ? '我' : m.role === 'tool' ? '›' : session.provider === 'codex' ? 'G' : 'C'}</span><b>{m.role === 'user' ? '你' : m.role === 'tool' ? '工具执行' : m.role === 'system' ? '运行信息' : providerLabel(session.provider)}</b><time>{new Date(m.createdAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</time></div>{m.role === 'tool' ? <details><summary>{m.text.split('\n')[0]?.slice(0, 130) || '查看工具事件'}</summary><pre>{m.text}</pre></details> : <Markdown text={m.role === 'user' ? m.userText ?? m.text : m.text}/>}</article>)}{session.error && <div className="inline-error">{session.error}</div>}{["unauthenticated", "error", "logging-in"].includes(state.auth[session.provider].status) && state.auth[session.provider].cwd === session.cwd && <ProviderAuthPanel provider={session.provider} auth={state.auth[session.provider]} cwd={session.cwd} autoCheck={false}/>}{['running', 'starting'].includes(session.status) && <div className="thinking"><span className="status-pulse"/>{session.status === 'starting' ? '正在连接本地 CLI…' : 'Agent 正在处理，你可以切换其他会话继续工作。'}</div>}
      {session.approvals.map(a => <div className="approval" key={a.id}><strong><ShieldCheck size={17}/>{a.title}</strong>{a.summary && <pre className="approval-summary">{a.summary}</pre>}<details><summary>查看请求详情</summary><pre>{a.details}</pre></details>{a.questions?.map(q => <label className="field" key={q.id}>{q.text}{a.method === 'cursor/ask_question' ? <select value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}><option value="">选择答案</option>{q.options.map(o => <option key={o}>{o}</option>)}</select> : <input list={'q-' + q.id} value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}/>}<datalist id={'q-' + q.id}>{q.options.map(o => <option value={o} key={o}/>)}</datalist></label>)}<div className="row">{a.options.map(o => <button key={o.id} className={o.kind === 'deny' ? 'secondary' : 'primary'} onClick={() => void run(() => api.call('session.answer', { id: session.id, requestId: a.id, option: o.id, answers }))}>{o.label}</button>)}</div></div>)}</div>
      {!session.closedAt && <div className="composer-wrap">{session.sources.length > 0 && <div className="source-chips">{session.sources.map(f => <button key={f.id} title={f.sourcePath + '\n' + f.sha256} disabled={f.id === session.projectBrief?.sourceId} className={selectedSources.includes(f.id) || f.id === session.projectBrief?.sourceId ? 'selected' : ''} onClick={() => setSelectedSources(selectedSources.includes(f.id) ? selectedSources.filter(x => x !== f.id) : [...selectedSources, f.id])}><Paperclip size={12}/>{f.name}{selectedSources.includes(f.id) && <Check size={12}/>}</button>)}</div>}<div className="composer"><textarea disabled={readOnly} aria-label="任务输入" placeholder="描述你的任务…" value={composer} onChange={e => setComposer(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.nativeEvent.keyCode !== 229) { e.preventDefault(); if (!e.repeat) void send(); } }}/><div className="composer-bottom"><button className="icon" title="添加本地参考文件" onClick={() => void run(async () => { const files = await api.call<any[]>('session.attachLocal', { id: session.id }); editInput(session.id, { sourceIds: [...(localInputs.current[session.id]?.sourceIds || selectedSources), ...files.map(f => f.id)] }); })}><Paperclip size={18}/></button><ComposerSettings key={session.id} session={session} readOnly={readOnly}/><span className="muted small composer-shortcut">Enter 发送 · Shift+Enter 换行</span><div className="spacer"/>{['running', 'approval', 'starting'].includes(session.status) ? <button className="send stop" title="停止当前任务" onClick={() => void run(() => api.call('session.stop', { id: session.id }))}><Square size={15}/></button> : <button className="send" title="发送任务" disabled={readOnly || !composer.trim() || sendingIds.includes(session.id)} onClick={() => void send()}><ArrowUp size={20}/></button>}</div></div>{(inputError || sendingIds.includes(session.id)) && <div className="composer-note">{inputError || "正在检查登录…"}</div>}</div>}</> : <div className="welcome"><span className="eyebrow">YOUR WORK, CONNECTED.</span><h1>个人探索，<br/><em>团队共享。</em></h1><button className="primary large" disabled={readOnly || !project} onClick={() => setNewOpen(true)}><Plus size={18}/>新建工作会话</button><div className="welcome-cards">{state.providers.map(p => <div key={p.provider}><span className={'provider-icon ' + p.provider}>{p.provider === 'codex' ? 'G' : 'C'}</span><b>{providerLabel(p.provider)}</b><span className={p.available ? 'green small' : 'muted small'}>{p.available ? '已检测到 CLI' : '待配置 CLI'}</span></div>)}</div><button className="text-button" onClick={() => setSettingsOpen(true)}>配置 CLI 与本地环境 <ChevronRight size={14}/></button></div>)}
    {view === 'drafts' && <div className="workspace-page"><div className="page-title"><div><span className="eyebrow">CONTRIBUTIONS</span><h1>整理成果</h1></div></div>{state.drafts.length ? <><select aria-label="选择成果草稿" className="draft-select" value={draftId} onChange={e => setDraftId(e.target.value)}>{state.drafts.map(d => <option value={d.id} key={d.id}>{d.title} · {draftStatus(d, state.transfers.find(t => t.id === d.submitted))}</option>)}</select>{draft && <DraftEditor key={draft.id} draft={draft} transfer={state.transfers.find(t => t.id === draft.submitted)} sourceSession={state.sessions.find(s => s.id === draft.sessionId)} sourceTitle={state.sessions.find(s => s.id === draft.sessionId)?.title} session={state.sessions.find(s => s.id === draft.prepareSessionId)} run={run} notice={setNotice} close={() => { const source = state.sessions.find(s => s.id === draft.sessionId); if (source) { setShowClosed(!!source.closedAt); selectSession(source); } else setView('sessions'); }}/>}</> : <div className="page-empty"><FileArchive size={38}/><h2>还没有成果草稿</h2><p>在会话中点击“整理成果”。</p><button className="secondary" onClick={() => setView('sessions')}>返回工作会话</button></div>}</div>}
    {view === 'transfers' && <div className="workspace-page"><div className="page-title"><div><span className="eyebrow">TRANSFER CENTER</span><h1>传输记录</h1></div><span className="muted">每项任务固定绑定项目与账号</span></div><div className="row"><span className="muted small">上传缓存：{bytes(state.transfers.filter(t => !t.cacheCleared).reduce((n, t) => n + t.total, 0))}</span><button className="secondary compact" onClick={() => void run(async () => { const result = await api.call<{ count: number; bytes: number }>('cache.clean'); setNotice(`已清理 ${result.count} 个成功上传的缓存，释放 ${bytes(result.bytes)}；会话和草稿仍保留`); })}>清理成功上传缓存</button></div>{!state.transfers.length && <div className="page-empty"><Upload size={38}/><h2>没有传输任务</h2></div>}{state.transfers.map(t => <div className="transfer-card" key={t.id}><div className="row"><FileArchive size={22}/><b>{t.name}</b><span className="spacer"/><span className={'badge ' + t.status}>{({ queued: '排队中', running: '正在传输', done: '已完成', error: '未完成' })[t.status]}</span></div><p>{t.projectName} · {t.binding.username}@{t.binding.host}</p><code>{t.target}</code><progress max={t.total || 1} value={t.bytes}/><div className="row"><span className="muted small">{bytes(t.bytes)} / {bytes(t.total)} · {new Date(t.createdAt).toLocaleString()}</span><span className="spacer"/>{t.status === 'error' && <button className="secondary compact" onClick={() => void run(() => api.call('transfer.retry', { id: t.id }))}><RefreshCw size={13}/>重试</button>}</div>{t.cacheCleared && <p className="muted small">本机上传缓存已清理，远端内容仍保留。</p>}{t.error && <div className="inline-error">{t.error}</div>}</div>)}</div>}
    </main>
    {preview && <aside className="inspector"><header><div><span className="eyebrow">FILE PREVIEW</span><h3>{preview.name}</h3></div><button className="icon" title="关闭预览" onClick={() => setPreview(undefined)}><PanelRightClose size={18}/></button></header><div className="file-meta"><code>{preview.path}</code><span>{bytes(preview.size)} · {connection?.profile.mode === 'local' ? '本地共享文件' : '远端文件'}</span></div><div className="preview-content">{preview.type === 'image' ? <img src={preview.content} alt={preview.name}/> : preview.type === 'text' ? /\.md$/i.test(preview.name) ? <Markdown text={preview.content}/> : <pre>{preview.content}</pre> : <div className="page-empty"><FileArchive size={34}/><p>此格式请下载后查看</p></div>}{preview.truncated && <p className="muted small">仅显示前 512 KB，下载可获取完整文件。</p>}</div><footer>{projectAdmin && <button className="secondary" onClick={() => void run(async () => { await api.call('content.adopt', { projectId: previewOrigin, path: preview.path }); setPreview(undefined); setView('library'); setNotice('已纳入公共成果，点击条目即可整理、替换或删除'); })}>纳入公共成果管理</button>}<button className="primary" disabled={!session || !!session.closedAt || session.purpose === 'prepare' || previewOrigin !== session.binding?.project.id} onClick={() => void run(async () => { const file = await api.call<any>('session.attachRemote', { id: session!.id, projectId: previewOrigin, path: preview.path }); setSelectedSources([...selectedSources, file.id]); setNotice('已下载快照并选入当前会话，下次发送时引用'); })}><Link size={15}/>加入当前会话</button><button className="secondary" onClick={() => void run(() => api.call('remote.download', { projectId: previewOrigin, path: preview.path }))}><Download size={15}/>下载</button></footer></aside>}
    </div><footer className="statusbar"><span><span className={'dot ' + (connection?.connected ? 'green-dot' : '')}/>{connection?.connected ? '共享空间已连接' : '本地工作模式'}</span><span>{workSessions.filter(s => ['running', 'starting'].includes(s.status)).length} 个会话运行中 · {state.drafts.filter(d => d.generation === 'running').length} 项成果整理中</span><span className="spacer"/><span>{connection?.profile.mode === 'local' ? '本地文件系统 · 模拟权限' : '文件权限由 Linux 执行'}</span></footer></div>
    {notice && <div className="toast"><span>{notice}</span><button className="icon" title="关闭提示" onClick={() => setNotice('')}><X size={16}/></button></div>}
    {closingSession && <Modal title="停止并关闭会话" close={() => setClosingSession(undefined)}><div className="modal-body"><p>“{closingSession.title}”正在运行。关闭将停止当前任务，已保存的对话和 Agent 工作记录仍可重新打开。正在执行的操作可能已经产生部分改动。</p></div><footer><button className="secondary" onClick={() => setClosingSession(undefined)}>继续工作</button><button className="primary" onClick={() => void run(async () => { await api.call('session.close', { id: closingSession.id }); setClosingSession(undefined); })}>停止并关闭</button></footer></Modal>}
    {connectOpen && <ConnectModal settings={state.settings} connection={connection} close={() => setConnectOpen(false)} run={run} onConnected={() => { setConnectOpen(false); void refresh(); }}/> }
    {onboarding && onboardingWorkspace && connection?.connected && <ProjectOnboarding key={onboarding.contextKey} profile={connection.profile} workspace={onboardingWorkspace} close={() => setOnboarding(undefined)} created={async p => { await refresh(); setProjectId(p.id); setOnboarding(undefined); setNotice('项目说明、成果目录与轨迹目录已创建，本组成员可查看项目资料'); }}/>}
    {projectCreateOpen && <ProjectBriefEditor groups={creatableGroups} initialGroup={createGroup} admin close={() => setProjectCreateOpen(false)} saved={async p => { await refresh(); if (p) setProjectId(p.id); setProjectCreateOpen(false); setNotice('项目与公共成果、轨迹目录已创建'); }}/>}
    {briefOpen && project && <ProjectBriefEditor key={project.id} project={project} groups={workspaces} admin={projectAdmin} close={() => setBriefOpen(false)} saved={async () => { await refresh(); setBriefOpen(false); setNotice('项目资料新版本已保存'); }}/>}
    {settingsOpen && <SettingsModal settings={state.settings} providers={state.providers} auth={state.auth} close={() => setSettingsOpen(false)} run={run}/>}
    {newOpen && <NewSessionModal settings={state.settings} auth={state.auth} projects={projects} projectId={projectId} close={() => setNewOpen(false)} run={run} created={s => { setShowClosed(false); setSessionId(s.id); setView('sessions'); setNewOpen(false); void refresh(); }}/>}
    {handoff && <AgentNotesPanel key={handoff.id} handoff={handoff} close={() => setHandoff(undefined)}/>}

    {history && <Modal title="轨迹上传" wide close={() => setHistory(undefined)}><div className="modal-body"><p className="muted">上传本会话的对话和工具记录，本组成员可查看。</p><label className="check-row"><input type="checkbox" disabled={!state.sessions.find(s => s.id === history.id)?.binding} checked={!!state.sessions.find(s => s.id === history.id)?.autoUpload} onChange={e => void run(() => api.call('session.autoUpload', { id: history.id, enabled: e.target.checked }))}/>此会话自动上传</label><label className="field">自动上传最短间隔<select aria-label="轨迹自动上传间隔" value={state.settings.autoUploadMinutes || 15} onChange={e => void run(() => api.call('settings.save', { ...state.settings, autoUploadMinutes: Number(e.target.value) }))}>{[1, 5, 15, 30, 60].map(n => <option value={n} key={n}>{n} 分钟</option>)}</select></label><p className="muted small">最近成功上传：{state.sessions.find(s => s.id === history.id)?.lastArchiveAt ? new Date(state.sessions.find(s => s.id === history.id)!.lastArchiveAt!).toLocaleString() : '尚无成功记录'}。</p><div className="history-preview"><Markdown text={history.text}/></div></div><footer><button className="primary" disabled={!state.sessions.find(s => s.id === history.id)?.binding} onClick={() => void run(async () => { await api.call('session.uploadTrajectory', { id: history.id }); setHistory(undefined); setView('transfers'); })}><Upload size={15}/>确认上传轨迹</button></footer></Modal>}
  </div>;
}
type Run = <T>(fn: () => Promise<T>) => Promise<T | undefined>;
function ConnectModal({ settings, connection, close, run, onConnected }: { settings: Settings; connection: Snapshot['connection']; close: () => void; run: Run; onConnected: () => void }) {
  const empty: ConnectionProfile = { id: crypto.randomUUID(), name: '团队共享空间', host: '', port: 22, username: '', fingerprint: '', manifestPath: '', projects: [], workPath: '' };
  const [profile, setProfile] = useState(connection?.profile || settings.connections[0] || empty);
  const [localPath, setLocalPath] = useState(settings.localWorkspace || ''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [manual, setManual] = useState(false);
  const local = profile.mode === 'local';
  const configured = !!profile.host;
  const profiles = settings.connections;
  const saved = profiles.some(p => p.id === profile.id);
  const connectionLabel = (p: ConnectionProfile) => `${p.mode === 'local' ? '本地测试团队' : p.host + ':' + p.port} · ${p.username || '待填写账号'}`;
  const select = (p: ConnectionProfile) => { setProfile(p); setPassword(''); setError(''); setManual(false); };
  const update = (key: keyof ConnectionProfile, value: unknown) => setProfile({ ...profile, [key]: value, ...(['host', 'port'].includes(key) ? { fingerprint: '' } : {}) });
  const choose = (setter: (value: string) => void) => void run(async () => { const dir = await api.call<string>('choose.directory'); if (dir) setter(dir); });
  return <Modal title="团队账号与本机目录" close={close} wide><div className="modal-body">
    {error && <div className="inline-error" role="alert">{error}</div>}
    <fieldset className="connection-fields" disabled={busy}>
    {profiles.length > 1 && <label className="field">团队连接（已保存）<select aria-label="团队连接（已保存）" value={saved ? profile.id : ''} onChange={e => { const p = profiles.find(x => x.id === e.target.value); if (p) select(p); }}>
      {!saved && <option value="" disabled>正在设置新连接</option>}{profiles.map(p => <option key={p.id} value={p.id}>{connectionLabel(p)} · {p.name}</option>)}
    </select></label>}
    <div className="callout" aria-label="团队连接说明"><Server size={19}/><div><b>{configured ? '团队连接：' + connectionLabel(profile) : '尚未配置团队连接'}</b>{!configured && <small>请导入管理员提供的连接配置。</small>}</div></div>
    <div className="row gap-bottom"><button className="secondary" onClick={() => void run(async () => { const p = await api.call<ConnectionProfile | null>('profile.import'); if (p) select(p); })}>导入管理员配置</button><button className="text-button" onClick={() => { select({ ...empty, mode: 'sftp' }); setManual(true); }}>手动设置 SSH 连接</button>{profiles.length === 1 && !saved && <button className="text-button" onClick={() => select(profiles[0])}>返回已有团队连接</button>}</div>
    {local && !profile.localRoot?.trim() && <div className="inline-error" role="alert">管理员配置缺少共享目录，请重新导入完整的连接配置。</div>}
    {!local && (configured || manual) && <details className="connection-server-details" open={manual} onToggle={e => setManual(e.currentTarget.open)}><summary>服务器连接设置</summary><div className="form-grid">
      <label className="field">服务器地址<input value={profile.host} onChange={e => update('host', e.target.value)}/></label><label className="field">SFTP 端口<input type="number" value={profile.port} onChange={e => update('port', Number(e.target.value))}/></label>
      <label className="field full">管理员提供的服务器指纹<input value={profile.fingerprint} onChange={e => update('fingerprint', e.target.value)}/></label>
    </div></details>}
    <div className="form-grid">
      <label className="field full">本机工作路径（必填）<div className="row"><input aria-label="本机工作路径" value={localPath} onChange={e => setLocalPath(e.target.value)}/><button className="secondary" onClick={() => choose(setLocalPath)}>选择目录</button></div></label>

      <label className="field">{'成员账号'}<input aria-label={'成员账号'} placeholder="管理员分配的姓名或工号" value={profile.username} onChange={e => update('username', e.target.value)}/></label>
      <label className="field">登录密码<input aria-label="登录密码" type="password" autoComplete="off" value={password} onChange={e => setPassword(e.target.value)}/></label>
    </div>
    </fieldset>
  </div><footer>{connection?.connected && <button className="secondary" onClick={() => void run(async () => { await api.call('remote.disconnect'); close(); })}><Unplug size={14}/>断开连接</button>}<span className="spacer"/><button className="secondary" onClick={close}>取消</button><button className="primary" disabled={busy || !profile.host || !profile.username || !password || !localPath.trim() || (local && !profile.localRoot?.trim())} onClick={async () => { setBusy(true); setError(''); try { await api.call('remote.connect', { profile: { ...profile, projects: [], workPath: '', manifestPath: '' }, password, localPath }); setPassword(''); onConnected(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}>{busy ? '正在登录并发现工作组…' : '登录并发现工作组'}</button></footer></Modal>;
}

function SettingsModal({ settings, providers, auth, close, run }: { settings: Settings; providers: Snapshot['providers']; auth: Snapshot['auth']; close: () => void; run: Run }) {
  const [paths, setPaths] = useState(settings.providerPaths), [busy, setBusy] = useState(false);
  return <Modal title="CLI 与本地设置" close={close} wide><div className="modal-body">{(['codex', 'cursor'] as Provider[]).map(provider => { const info = providers.find(x => x.provider === provider); return <div className="provider-setting" key={provider}><div className="row"><span className={'provider-icon ' + provider}>{provider === 'codex' ? 'G' : 'C'}</span><strong>{providerLabel(provider)}</strong><span className="spacer"/><span className={'badge ' + (info?.available ? 'done' : 'error')}>{info?.available ? '已检测到 CLI' : '未找到 CLI'}</span></div><label className="field">CLI 程序路径<div className="row"><input placeholder="留空自动检测" value={paths[provider]} onChange={e => setPaths({ ...paths, [provider]: e.target.value })}/><button className="secondary" onClick={() => void run(async () => { const file = await api.call<string>('choose.executable'); if (file) setPaths({ ...paths, [provider]: file }); })}>选择</button></div></label><p className="muted small break">{info?.available ? info.path + '\n' + info.version : info?.detail}</p><ProviderAuthPanel provider={provider} auth={auth[provider]} cwd={settings.localWorkspace} stale={paths[provider] !== settings.providerPaths[provider]} beforeAction={async () => { await api.call('settings.save', { ...settings, providerPaths: paths }); }}/><div className="row"><button className="text-button" onClick={() => void api.call('open.link', provider === 'codex' ? 'https://developers.openai.com/codex/cli' : 'https://cursor.com/docs/cli/installation')}>官方安装说明</button></div></div>; })}<div className="callout"><HardDrive size={18}/><div>本机数据</div><button className="secondary compact" onClick={() => void api.call('open.data')}>打开目录</button></div></div><footer><button className="primary" disabled={busy} onClick={() => void run(async () => { setBusy(true); try { await api.call('settings.save', { ...settings, providerPaths: paths }); await api.call('providers.detect'); await Promise.all((['codex', 'cursor'] as Provider[]).map(provider => api.call('provider.auth', { provider, cwd: settings.localWorkspace }))); } finally { setBusy(false); } })}>{busy ? '检测中…' : '保存并检测 CLI'}</button></footer></Modal>;
}
function NewSessionModal({ settings, auth, projects, projectId, close, run, created }: { settings: Settings; auth: Snapshot['auth']; projects: Project[]; projectId: string; close: () => void; run: Run; created: (s: AgentSession) => void }) {
  const [permissionMode, setPermissionMode] = useState<PermissionMode>('inherit');
  const [includeBrief, setIncludeBrief] = useState(true);
  const [selected, setSelected] = useState<Provider>('codex'), [cwd, setCwd] = useState(settings.lastWorkspace || settings.localWorkspace || ''), [project, setProject] = useState(projectId), [busy, setBusy] = useState(false), [model, setModel] = useState('');
  useEffect(() => { if (selected === 'cursor' && permissionMode === 'auto') setPermissionMode('inherit'); }, [selected, permissionMode]);
  useEffect(() => setModel(''), [selected, cwd]);
  return <Modal title="新建工作会话" close={close} wide><div className="modal-body">
    <div className="provider-picker">{(['codex', 'cursor'] as Provider[]).map(p => <button aria-label={providerLabel(p)} className={selected === p ? 'selected' : ''} key={p} onClick={() => setSelected(p)}><span className={'provider-icon ' + p}>{p === 'codex' ? 'G' : 'C'}</span>{providerLabel(p)}{selected === p && <Check size={15}/>}</button>)}</div>
    <div className="new-session-grid"><div>
      <ProviderAuthPanel key={selected} provider={selected} auth={auth[selected]} cwd={cwd}/>
      <label className="field">本地工作目录<div className="row"><input aria-label="本地工作目录" placeholder="选择代码或资料所在目录" value={cwd} onChange={e => setCwd(e.target.value)}/><button className="secondary" title="选择本地工作目录" onClick={() => void run(async () => { const dir = await api.call<string>('choose.directory'); if (dir) setCwd(dir); })}><FolderOpen size={17}/></button></div></label>
      <label className="field">绑定共享项目<select aria-label="绑定共享项目" value={project} onChange={e => { setProject(e.target.value); const directory = Object.entries(settings.projectDirectories || {}).find(([key]) => key.endsWith(':' + e.target.value))?.[1]; if (directory) setCwd(directory); }}><option value="" disabled>请选择工作组下的项目</option>{[...new Set(projects.map(p => p.groupName || ''))].map(g => <optgroup key={g} label={projects.find(p => (p.groupName || '') === g)?.groupLabel || '项目'}>{projects.filter(p => (p.groupName || '') === g).map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</optgroup>)}</select></label>
      <label className="check-row"><input type="checkbox" checked={includeBrief} onChange={e => setIncludeBrief(e.target.checked)}/>默认引用项目资料（已完善时）</label>
    </div><ModelPicker key={selected + cwd} provider={selected} cwd={cwd} ready={!!canUseProvider(auth[selected]) && auth[selected].cwd === cwd} model={model} changed={setModel}/></div>
    <PermissionPicker key={selected + cwd} provider={selected} cwd={cwd} mode={permissionMode} changed={setPermissionMode}/>
  </div><footer><button className="secondary" onClick={close}>取消</button><button className="primary" disabled={!cwd || !project || busy || !canUseProvider(auth[selected]) || auth[selected].cwd !== cwd} onClick={() => void run(async () => { setBusy(true); try { const s = await api.call<AgentSession>('session.create', { provider: selected, cwd, model: model || undefined, permissionMode, includeBrief, projectId: project || undefined }); created(s); } finally { setBusy(false); } })}>创建会话</button></footer></Modal>;
}
function AgentNotesPanel({ handoff, close }: { handoff: { id: string; text: string }; close: () => void }) {
  const key = useRef('handoff:' + handoff.id + ':' + crypto.randomUUID());
  const editor = useAutosave(key.current, handoff.text, text => api.call('handoff.save', { id: handoff.id, text }));
  const [error, setError] = useState(''), [editing, setEditing] = useState(false);
  const finish = async () => { try { await editor.flush(); close(); } catch (e: any) { setError('文件尚未保存，窗口已保留：' + e.message); } };
  return <Modal title="Agent 工作记录" wide close={() => void finish()}><div className="modal-body"><div className="agent-notes-explanation"><span className="badge">本地过程资料</span><p>Agent 维护的过程记录，不随成果上传。</p></div>{error && <div role="alert" className="inline-error">{error}</div>}{editing ? <><label className="field">更正工作记录<textarea className="editor handoff-editor" aria-label="Agent 工作记录正文" value={editor.value} onChange={e => editor.change(e.target.value)}/></label><p className="muted small">修改后需重新整理成果。</p><p role="status">{editor.status}</p>{editor.status.startsWith('保存失败') && <button className="secondary" onClick={editor.retry}>重试保存</button>}</> : <div className="agent-notes-preview" aria-label="Agent 工作记录预览"><Markdown text={editor.value || '暂无工作记录。'}/></div>}</div><footer>{!editing && <button className="secondary" onClick={() => setEditing(true)}>更正记录（可选）</button>}<button className="primary" onClick={() => void finish()}>{editing ? '保存并返回' : '返回会话'}</button></footer></Modal>;
}
createRoot(document.getElementById('root')!).render(<App/>);
