import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Folder, FolderOpen, FileText, Plus, Settings as SettingsIcon, ArrowUp, ArrowLeft, RefreshCw, Upload, Download, Link, X, Check, ChevronRight, MessageSquare, Layers, Server, Unplug, Search, Paperclip, Square, ShieldCheck, FileArchive, HardDrive, PanelRightClose, Activity, Sparkles, ExternalLink, Copy, Terminal, CircleHelp } from 'lucide-react';
import type { AgentSession, ConnectionProfile, Draft, FilePreview, Project, Provider, RemoteEntry, Settings, Snapshot } from '../shared/types';
import './styles.css';
import { DraftEditor, draftStatus } from './draft-editor';
import { ModelPicker } from './model-picker';
import { useAutosave } from './autosave';
import type { SessionInput } from '../shared/types';
import { ProviderAuthPanel, canUseProvider } from './provider-auth';
const api = window.workbench;
const bytes = (n: number) => n < 1024 ? n + ' B' : n < 1024 ** 2 ? (n / 1024).toFixed(1) + ' KB' : (n / 1024 ** 2).toFixed(1) + ' MB';
const providerLabel = (p: Provider) => p === 'codex' ? 'Codex · GPT' : 'Cursor';
const statusLabels = { idle: '就绪', starting: '连接 CLI', running: '处理中', approval: '等待操作确认', error: '需要处理' };
function Markdown({ text }: { text: string }) { return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ href, children }) => <a href={href} onClick={e => { e.preventDefault(); if (href && /^https?:/.test(href)) void api.call('open.link', href); }}>{children}<ExternalLink size={11} /></a>, img: ({ alt }) => <span>[图片：{alt || '附件'}]</span> }}>{text}</ReactMarkdown></div>; }
function Modal({ title, children, close, wide = false }: { title: string; children: React.ReactNode; close: () => void; wide?: boolean }) { return <div className="modal-backdrop"><section className={'modal ' + (wide ? 'wide' : '')}><header><h2>{title}</h2><button className="icon" aria-label="关闭窗口" onClick={close}><X size={19}/></button></header>{children}</section></div>; }
function App() {
  const [state, setState] = useState<Snapshot>(); const [notice, setNotice] = useState('');
  const [view, setView] = useState<'sessions' | 'drafts' | 'transfers'>('sessions'); const [sessionId, setSessionId] = useState('');
  const [projectId, setProjectId] = useState(''); const [remoteDir, setRemoteDir] = useState(''); const [entries, setEntries] = useState<RemoteEntry[]>([]); const [fileError, setFileError] = useState(''); const [loadingFiles, setLoadingFiles] = useState(false);
  const [preview, setPreview] = useState<FilePreview>(); const [previewOrigin, setPreviewOrigin] = useState(''); const [search, setSearch] = useState('');
  const [settingsOpen, setSettingsOpen] = useState(false); const [connectOpen, setConnectOpen] = useState(false); const [newOpen, setNewOpen] = useState(false);
  const [busy, setBusy] = useState(false); const [inputVersion, updateInputs] = useState(0); const localInputs = useRef<Record<string, SessionInput>>({}); const [sendingIds, setSendingIds] = useState<string[]>([]); const [inputError, setInputError] = useState('');
  const [handoff, setHandoff] = useState<{ id: string; text: string }>(); const [history, setHistory] = useState<{ id: string; text: string }>();
  const [draftId, setDraftId] = useState('');
  const [showClosed, setShowClosed] = useState(false), [closingSession, setClosingSession] = useState<AgentSession>();
  const [projectCreateOpen, setProjectCreateOpen] = useState(false);
  const fileRequest = useRef(0), previewRequest = useRef(0), scroller = useRef<HTMLDivElement>(null); const snapshotSequence = useRef(0);
  const refresh = async () => { const n = ++snapshotSequence.current; const next = await api.call<Snapshot>('snapshot'); if (n === snapshotSequence.current) setState(next); };
  const run = async <T,>(fn: () => Promise<T>): Promise<T | undefined> => { try { return await fn(); } catch (e: any) { setNotice(e.message); return undefined; } };
  useEffect(() => { void api.call<Snapshot>('snapshot').then(next => { setState(next); setConnectOpen(!next.workspaceReady); }); return api.subscribe(event => { if (event.type === 'state') void refresh(); else setNotice(event.message); }); }, []);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 15000); return () => clearTimeout(timer); }, [notice]);
  const connection = state?.connection, projects = connection?.connected ? connection.profile.projects : [], project = projects.find(p => p.id === projectId);
  const session = state?.sessions.find(s => s.id === sessionId), draft = state?.drafts.find(d => d.id === draftId);
  const workSessions = state?.sessions.filter(s => s.purpose === 'work') || [];
  const preparingCount = state?.drafts.filter(d => !d.submitted && d.generation === 'running').length || 0;
  const readyCount = state?.drafts.filter(d => !d.submitted && d.generation === 'ready').length || 0;
  const sessionDraft = state?.drafts.find(d => d.sessionId === sessionId && !d.submitted);
  const visibleSessions = workSessions.filter(s => showClosed ? !!s.closedAt : !s.closedAt);
  useEffect(() => { if (!visibleSessions.some(s => s.id === sessionId)) setSessionId(visibleSessions[0]?.id || ''); }, [JSON.stringify(visibleSessions.map(s => s.id))]);
  const currentInput = localInputs.current[sessionId] || state?.inputs[sessionId] || { text: '', sourceIds: [], answers: {} };
  const composer = currentInput.text, selectedSources = currentInput.sourceIds, answers = currentInput.answers;
  const editInput = (id: string, patch: Partial<SessionInput>) => {
    const value = { ...(localInputs.current[id] || state?.inputs[id] || { text: '', sourceIds: [], answers: {} }), ...patch };
    localInputs.current[id] = value; updateInputs(n => n + 1);
    void api.call('session.input', { id, input: value }).then(() => setInputError(''), (e: Error) => setInputError('输入保存失败，请保留当前窗口并重试：' + e.message));
  };
  const setComposer = (text: string) => editInput(sessionId, { text });
  const setSelectedSources = (sourceIds: string[]) => editInput(sessionId, { sourceIds });
  const setAnswers = (answers: Record<string, string>) => editInput(sessionId, { answers });
  useEffect(() => { if (!projects.some(p => p.id === projectId)) setProjectId(projects[0]?.id || ''); }, [connection?.connected, JSON.stringify(projects)]);
  useEffect(() => { setPreview(undefined); previewRequest.current++; setRemoteDir(project?.remoteRoot || ''); }, [projectId, connection?.profile.id, connection?.profile.username]);
  const loadFiles = async () => {
    const n = ++fileRequest.current; if (!project || !remoteDir) { setEntries([]); return; }
    setLoadingFiles(true); setFileError('');
    try { const items = await api.call<RemoteEntry[]>('remote.list', { projectId: project.id, path: remoteDir }); if (fileRequest.current === n) setEntries(items); }
    catch (e: any) { if (fileRequest.current === n) { setFileError(e.message); setEntries([]); } }
    finally { if (fileRequest.current === n) setLoadingFiles(false); }
  };
  useEffect(() => { void loadFiles(); return () => { fileRequest.current++; }; }, [remoteDir, projectId, connection?.connected]);
  useEffect(() => { const timer = setInterval(() => { if (document.visibilityState === 'visible' && connection?.connected) void loadFiles(); }, 30000); return () => clearInterval(timer); }, [remoteDir, projectId, connection?.connected]);
  useEffect(() => { if (scroller.current) scroller.current.scrollTop = scroller.current.scrollHeight; }, [session?.messages.length, session?.messages.at(-1)?.text]);
  const selectSession = (s: AgentSession) => { setSessionId(s.id); setView('sessions'); if (s.binding && projects.some(p => p.id === s.binding!.project.id)) setProjectId(s.binding.project.id); };
  const send = async () => {
    if (!session || !composer.trim() || sendingIds.includes(session.id)) return;
    const id = session.id, sent = { ...currentInput }; setSendingIds(ids => [...ids, id]);
    const result = await run(() => api.call('session.send', { id, text: sent.text, sourceIds: sent.sourceIds }));
    // Bind the acknowledgement to the original session, and preserve edits typed while waiting.
    const latest = localInputs.current[id] || state?.inputs[id] || sent;
    if (result && latest.text === sent.text && JSON.stringify(latest.sourceIds) === JSON.stringify(sent.sourceIds)) editInput(id, { text: '', sourceIds: [] });
    setSendingIds(ids => ids.filter(x => x !== id));
  };
  const openFile = async (item: RemoteEntry) => {
    if (item.kind === 'directory') { setRemoteDir(item.path); return; }
    if (item.kind === 'link') { setNotice('第一版不直接打开符号链接，请管理员提供实际目录或文件入口'); return; }
    const n = ++previewRequest.current; const selectedProject = projectId;
    const result = await run(() => api.call<FilePreview>('remote.preview', { projectId: selectedProject, path: item.path }));
    if (result && n === previewRequest.current) { setPreview(result); setPreviewOrigin(selectedProject); }
  };
  if (!state) return <div className="boot"><Layers size={34}/><p>正在启动团队工作台…</p></div>;
  if (!state.workspaceReady) return <div className="setup-gate"><div className="setup-card"><div className="welcome-symbol"><FolderOpen size={30}/></div><span className="eyebrow">WORKSPACE SETUP</span><h1>先配置工作路径</h1><p>填写本机工作目录和 Linux 工作目录。<br/>远端账号通过目录访问权限验证后，才能进入工作台。</p><button className="primary large" onClick={() => setConnectOpen(true)}>配置并验证工作路径</button></div>{connectOpen && <ConnectModal settings={state.settings} connection={connection} close={() => setConnectOpen(false)} run={run} onConnected={() => { setConnectOpen(false); void refresh(); }}/> }</div>;
  return <div className="app">
    <nav className="rail"><div className="brand-mark"><Layers size={25}/></div><button className={view === 'sessions' ? 'active' : ''} title="工作会话" onClick={() => setView('sessions')}><MessageSquare size={22}/></button><button className={view === 'drafts' ? 'active' : ''} title="整理成果" aria-label="成果草稿" onClick={() => { setView('drafts'); if (!state.drafts.some(d => d.id === draftId)) setDraftId(state.drafts[0]?.id || ''); }}><FileArchive size={22}/>{(preparingCount > 0 || readyCount > 0) && <span className="preparation-nav-badge" aria-label="成果提醒">{preparingCount ? "整理中" : "待确认"}</span>}</button><button className={view === 'transfers' ? 'active' : ''} title="传输记录" onClick={() => setView('transfers')}><Activity size={22}/></button><div className="rail-spacer"/><button title="设置" onClick={() => setSettingsOpen(true)}><SettingsIcon size={22}/></button><span className="avatar">我</span></nav>
    <div className="shell"><header className="topbar"><div><span className="eyebrow">TEAM AGENT WORKBENCH</span><strong>团队工作台 <span className="version">用户版</span></strong></div><div className="topbar-actions"><span className="privacy"><ShieldCheck size={14}/>个人账户 · 本地运行</span><button className={'connection-button ' + (connection?.connected ? 'online' : '')} onClick={() => setConnectOpen(true)}><span className="dot"/>{connection?.connected ? `${connection.profile.mode === 'local' ? '本地模拟 · ' : ''}${connection.profile.name} · ${connection.profile.username}` : '连接共享空间'}<ChevronRight size={14}/></button></div></header>
    <div className="body"><aside className="sidebar"><div className="sidebar-head"><h3>团队文件</h3><div className="row">{connection?.connected && connection.workspace?.canCreateProject && <button className="icon" title="创建远端项目" onClick={() => setProjectCreateOpen(true)}><Plus size={17}/></button>}<button className="icon" title="刷新文件" disabled={!project} onClick={() => void loadFiles()}><RefreshCw size={15} className={loadingFiles ? 'spin' : ''}/></button><button className="icon" title="刷新项目入口" disabled={!connection?.connected} onClick={() => void run(() => api.call('remote.manifest'))}><Server size={15}/></button></div></div>
      <select className="project-select" aria-label="当前远端项目" value={projectId} onChange={e => setProjectId(e.target.value)}><option value="">{connection?.connected ? '选择项目' : '尚未连接共享空间'}</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>
      {project ? <><div className="path-row"><button className="icon" title="上一级" disabled={remoteDir === project.remoteRoot} onClick={() => setRemoteDir(remoteDir.slice(0, remoteDir.lastIndexOf('/')) || project.remoteRoot)}><ArrowLeft size={14}/></button><span title={remoteDir}>{remoteDir.replace(project.remoteRoot, '') || '/'}</span><button className="icon" title="上传文件到当前目录" onClick={() => void run(async () => { await api.call('remote.upload', { projectId, folder: remoteDir }); setNotice('文件已加入上传队列'); setView('transfers'); })}><Upload size={15}/></button></div><label className="search"><Search size={14}/><input placeholder="筛选当前目录" value={search} onChange={e => setSearch(e.target.value)}/></label><div className="file-list">{fileError && <div className="inline-error">{fileError}</div>}{!loadingFiles && !entries.length && !fileError && <div className="muted small pad">此目录还没有文件</div>}{entries.filter(f => f.name.toLowerCase().includes(search.toLowerCase())).map(f => <button key={f.path} className={'file-row ' + (preview?.path === f.path ? 'selected' : '')} onClick={() => void openFile(f)} title={f.path}>{f.kind === 'directory' ? <Folder size={17}/> : <FileText size={17}/>}<span>{f.name}</span>{f.kind === 'directory' ? <ChevronRight size={13}/> : <small>{bytes(f.size)}</small>}</button>)}</div></> : <div className="remote-empty"><Server size={29}/><p>{connection?.connected ? "当前工作路径暂无项目" : "把团队资料带到手边"}</p>{connection?.workspace?.canCreateProject && <button className="primary" onClick={() => setProjectCreateOpen(true)}>创建第一个项目</button>}<span>使用管理员分配的账号，<br/>浏览共享空间中的项目目录。</span><button className="secondary" onClick={() => setConnectOpen(true)}>配置连接</button></div>}
      <div className="session-heading"><h3>本地会话</h3><button className="icon" title="新建会话" onClick={() => setNewOpen(true)}><Plus size={18}/></button></div><div className="session-list">{visibleSessions.map(s => <button className={'session-row ' + (sessionId === s.id && view === 'sessions' ? 'selected' : '')} key={s.id} data-session-id={s.id} onClick={() => selectSession(s)}><span className={'provider-icon ' + s.provider}>{s.provider === 'codex' ? 'G' : 'C'}</span><span><b>{s.title}</b><small>{s.binding?.project.name || '本地工作'} · {s.closedAt ? '已关闭' : providerLabel(s.provider)}</small></span>{['running', 'starting'].includes(s.status) && <span className="status-pulse"/>}{s.status === 'approval' && <CircleHelp size={15}/>}</button>)}{!visibleSessions.length && <p className="muted small pad">{showClosed ? '没有已关闭的会话。' : '没有打开的会话。从一个本地目录开始。'}</p>}</div><button className="closed-toggle text-button" onClick={() => setShowClosed(!showClosed)}>{showClosed ? '返回打开的会话' : `已关闭会话（${workSessions.filter(s => s.closedAt).length}）`}</button><div className="sidebar-footer"><HardDrive size={13}/><span>历史默认保存在本机</span></div>
    </aside>
    <main className="main-content">
    {view === 'sessions' && (session ? <><div className="session-toolbar"><div><h2>{session.title}</h2><span className="muted small" title={session.cwd}>{providerLabel(session.provider)} <span className="separator">/</span> {session.binding?.project.name || '本地会话'} <span className="separator">/</span> {session.closedAt ? '已关闭' : statusLabels[session.status]} <span className="separator">/</span> {session.model || 'CLI 默认模型'}</span></div><div className="row"><button className="secondary compact" onClick={() => void run(async () => setHandoff({ id: session.id, text: await api.call<string>('handoff.read', { id: session.id }) }))}><FileText size={14}/>交接文件</button><button className="secondary compact" onClick={() => void run(async () => setHistory({ id: session.id, text: await api.call<string>('session.history', { id: session.id }) }))}><Upload size={14}/>轨迹上传</button>{session.closedAt ? <button className="secondary compact" onClick={() => void run(async () => { await api.call('session.reopen', { id: session.id }); setShowClosed(false); })}>重新打开会话</button> : <button className="secondary compact" onClick={() => { if (['running', 'starting', 'approval'].includes(session.status)) setClosingSession(session); else void run(() => api.call('session.close', { id: session.id })); }}><X size={14}/>关闭会话</button>}<button aria-label="整理成果" className="primary compact" disabled={session.purpose === 'prepare' || busy} onClick={() => void run(async () => { setBusy(true); try { const d = await api.call<Draft>('draft.prepare', { id: session.id }); setDraftId(d.id); setView('drafts'); await refresh(); } finally { setBusy(false); } })}><Sparkles size={14}/>整理成果{sessionDraft && <span className="session-draft-status">{draftStatus(sessionDraft)}</span>}</button></div></div>
      <div className="messages" ref={scroller}>{!session.messages.length && <div className="session-welcome"><div className="welcome-symbol"><MessageSquare size={26}/></div><h2>开始这次工作</h2><p>描述任务，或从团队文件中选择资料。<br/>当前会话固定在这个本地目录中。</p><code>{session.cwd}</code></div>}{session.messages.map(m => <article key={m.id} className={'message ' + m.role}><div className="message-author"><span className={'provider-icon ' + (m.role === 'user' ? 'user' : session.provider)}>{m.role === 'user' ? '我' : m.role === 'tool' ? '›' : session.provider === 'codex' ? 'G' : 'C'}</span><b>{m.role === 'user' ? '你' : m.role === 'tool' ? '工具执行' : m.role === 'system' ? '运行信息' : providerLabel(session.provider)}</b><time>{new Date(m.createdAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</time></div>{m.role === 'tool' ? <details><summary>{m.text.split('\n')[0]?.slice(0, 130) || '查看工具事件'}</summary><pre>{m.text}</pre></details> : <Markdown text={m.text}/>}</article>)}{session.error && <div className="inline-error">{session.error}</div>}{["unauthenticated", "error", "logging-in"].includes(state.auth[session.provider].status) && state.auth[session.provider].cwd === session.cwd && <ProviderAuthPanel provider={session.provider} auth={state.auth[session.provider]} cwd={session.cwd} autoCheck={false}/>}{['running', 'starting'].includes(session.status) && <div className="thinking"><span className="status-pulse"/>{session.status === 'starting' ? '正在连接本地 CLI…' : 'Agent 正在处理，你可以切换其他会话继续工作。'}</div>}
      {session.approvals.map(a => <div className="approval" key={a.id}><strong><ShieldCheck size={17}/>{a.title}</strong><details><summary>查看请求详情</summary><pre>{a.details}</pre></details>{a.questions?.map(q => <label className="field" key={q.id}>{q.text}{a.method === 'cursor/ask_question' ? <select value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}><option value="">选择答案</option>{q.options.map(o => <option key={o}>{o}</option>)}</select> : <input list={'q-' + q.id} value={answers[q.id] || ''} onChange={e => setAnswers({ ...answers, [q.id]: e.target.value })}/>}<datalist id={'q-' + q.id}>{q.options.map(o => <option value={o} key={o}/>)}</datalist></label>)}<div className="row">{a.options.map(o => <button key={o.id} className={o.kind === 'deny' ? 'secondary' : 'primary'} onClick={() => void run(() => api.call('session.answer', { id: session.id, requestId: a.id, option: o.id, answers }))}>{o.label}</button>)}</div></div>)}</div>
      {!session.closedAt && <div className="composer-wrap">{session.sources.length > 0 && <div className="source-chips">{session.sources.map(f => <button key={f.id} title={f.sourcePath + '\n' + f.sha256} className={selectedSources.includes(f.id) ? 'selected' : ''} onClick={() => setSelectedSources(selectedSources.includes(f.id) ? selectedSources.filter(x => x !== f.id) : [...selectedSources, f.id])}><Paperclip size={12}/>{f.name}{selectedSources.includes(f.id) && <Check size={12}/>}</button>)}</div>}<div className="composer"><textarea aria-label="任务输入" placeholder="描述你的任务…" value={composer} onChange={e => setComposer(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); void send(); } }}/><div className="composer-bottom"><button className="icon" title="添加本地参考文件" onClick={() => void run(async () => { const files = await api.call<any[]>('session.attachLocal', { id: session.id }); editInput(session.id, { sourceIds: [...(localInputs.current[session.id]?.sourceIds || selectedSources), ...files.map(f => f.id)] }); })}><Paperclip size={18}/></button><span className="muted small">{providerLabel(session.provider)} · Ctrl + Enter 发送</span><div className="spacer"/>{['running', 'approval', 'starting'].includes(session.status) ? <button className="send stop" title="停止当前任务" onClick={() => void run(() => api.call('session.stop', { id: session.id }))}><Square size={15}/></button> : <button className="send" title="发送任务" disabled={!composer.trim() || sendingIds.includes(session.id)} onClick={() => void send()}><ArrowUp size={20}/></button>}</div></div><div className="composer-note">{inputError || (sendingIds.includes(session.id) ? "正在检查登录，输入保留至发送成功…" : "输入按会话自动保存；成果和会话记录分别提交。")}</div></div>}</> : <div className="welcome"><span className="eyebrow">YOUR WORK, CONNECTED.</span><h1>个人探索，<br/><em>团队共享。</em></h1><p>在熟悉的 Agent 中推进工作。<br/>需要的资料随手引用，值得共享的成果由你决定。</p><button className="primary large" onClick={() => setNewOpen(true)}><Plus size={18}/>新建工作会话</button><div className="welcome-cards">{state.providers.map(p => <div key={p.provider}><span className={'provider-icon ' + p.provider}>{p.provider === 'codex' ? 'G' : 'C'}</span><b>{providerLabel(p.provider)}</b><span className={p.available ? 'green small' : 'muted small'}>{p.available ? '已检测到 CLI' : '待配置 CLI'}</span></div>)}</div><button className="text-button" onClick={() => setSettingsOpen(true)}>配置 CLI 与本地环境 <ChevronRight size={14}/></button></div>)}
    {view === 'drafts' && <div className="workspace-page"><div className="page-title"><div><span className="eyebrow">CONTRIBUTIONS</span><h1>整理成果</h1></div><span className="muted">AI 整理 → 可选补充 → 确认上传</span></div>{state.drafts.length ? <><select aria-label="选择成果草稿" className="draft-select" value={draftId} onChange={e => setDraftId(e.target.value)}>{state.drafts.map(d => <option value={d.id} key={d.id}>{d.title} · {draftStatus(d)}</option>)}</select>{draft && <DraftEditor key={draft.id} draft={draft} sourceTitle={state.sessions.find(s => s.id === draft.sessionId)?.title} session={state.sessions.find(s => s.id === draft.prepareSessionId)} run={run} notice={setNotice}/>}</> : <div className="page-empty"><FileArchive size={38}/><h2>还没有成果草稿</h2><p>在工作会话中点击“整理成果”。Agent 会在后台读取交接文件和参考资料，自动生成说明并识别上传位置，你可以补充后确认上传。</p><button className="secondary" onClick={() => setView('sessions')}>返回工作会话</button></div>}</div>}
    {view === 'transfers' && <div className="workspace-page"><div className="page-title"><div><span className="eyebrow">TRANSFER CENTER</span><h1>传输记录</h1></div><span className="muted">每项任务固定绑定项目与账号</span></div>{!state.transfers.length && <div className="page-empty"><Upload size={38}/><h2>没有传输任务</h2><p>上传成果或上传轨迹后，可以在这里查看进度和重试。</p></div>}{state.transfers.map(t => <div className="transfer-card" key={t.id}><div className="row"><FileArchive size={22}/><b>{t.name}</b><span className="spacer"/><span className={'badge ' + t.status}>{({ queued: '排队中', running: '正在传输', done: '已完成', error: '未完成' })[t.status]}</span></div><p>{t.projectName} · {t.binding.username}@{t.binding.host}</p><code>{t.target}</code><progress max={t.total || 1} value={t.bytes}/><div className="row"><span className="muted small">{bytes(t.bytes)} / {bytes(t.total)} · {new Date(t.createdAt).toLocaleString()}</span><span className="spacer"/>{t.status === 'error' && <button className="secondary compact" onClick={() => void run(() => api.call('transfer.retry', { id: t.id }))}><RefreshCw size={13}/>重试</button>}</div>{t.error && <div className="inline-error">{t.error}</div>}</div>)}</div>}
    </main>
    {preview && <aside className="inspector"><header><div><span className="eyebrow">FILE PREVIEW</span><h3>{preview.name}</h3></div><button className="icon" title="关闭预览" onClick={() => setPreview(undefined)}><PanelRightClose size={18}/></button></header><div className="file-meta"><code>{preview.path}</code><span>{bytes(preview.size)} · {connection?.profile.mode === 'local' ? '本地共享文件' : '远端文件'}</span></div><div className="preview-content">{preview.type === 'image' ? <img src={preview.content} alt={preview.name}/> : preview.type === 'text' ? /\.md$/i.test(preview.name) ? <Markdown text={preview.content}/> : <pre>{preview.content}</pre> : <div className="page-empty"><FileArchive size={34}/><p>此格式请下载后查看</p></div>}{preview.truncated && <p className="muted small">仅显示前 512 KB，下载可获取完整文件。</p>}</div><footer><button className="primary" disabled={!session || !!session.closedAt || session.purpose === 'prepare' || previewOrigin !== session.binding?.project.id} onClick={() => void run(async () => { const file = await api.call<any>('session.attachRemote', { id: session!.id, projectId: previewOrigin, path: preview.path }); setSelectedSources([...selectedSources, file.id]); setNotice('已下载快照并选入当前会话，下次发送时引用'); })}><Link size={15}/>加入当前会话</button><button className="secondary" onClick={() => void run(() => api.call('remote.download', { projectId: previewOrigin, path: preview.path }))}><Download size={15}/>下载</button></footer></aside>}
    </div><footer className="statusbar"><span><span className={'dot ' + (connection?.connected ? 'green-dot' : '')}/>{connection?.connected ? '共享空间已连接' : '本地工作模式'}</span><span>{workSessions.filter(s => ['running', 'starting'].includes(s.status)).length} 个会话运行中 · {state.drafts.filter(d => d.generation === 'running').length} 项成果整理中</span><span className="spacer"/><span>{connection?.profile.mode === 'local' ? '本地文件系统 · 模拟权限' : '文件权限由 Linux 执行'}</span></footer></div>
    {notice && <div className="toast"><span>{notice}</span><button className="icon" title="关闭提示" onClick={() => setNotice('')}><X size={16}/></button></div>}
    {closingSession && <Modal title="停止并关闭会话" close={() => setClosingSession(undefined)}><div className="modal-body"><p>“{closingSession.title}”正在运行。关闭将停止当前任务，已保存的对话和交接文件仍可重新打开。正在执行的操作可能已经产生部分改动。</p></div><footer><button className="secondary" onClick={() => setClosingSession(undefined)}>继续工作</button><button className="primary" onClick={() => void run(async () => { await api.call('session.close', { id: closingSession.id }); setClosingSession(undefined); })}>停止并关闭</button></footer></Modal>}
    {connectOpen && <ConnectModal settings={state.settings} connection={connection} close={() => setConnectOpen(false)} run={run} onConnected={() => { setConnectOpen(false); void refresh(); }}/> }
    {projectCreateOpen && <CreateProjectModal workspace={connection?.workspace?.canonicalPath || ''} close={() => setProjectCreateOpen(false)} created={async p => { await refresh(); setProjectId(p.id); setProjectCreateOpen(false); setNotice('项目与轨迹目录已在共享区创建'); }}/>}
    {settingsOpen && <SettingsModal settings={state.settings} providers={state.providers} auth={state.auth} close={() => setSettingsOpen(false)} run={run}/>}
    {newOpen && <NewSessionModal settings={state.settings} auth={state.auth} projects={projects} projectId={projectId} close={() => setNewOpen(false)} run={run} created={s => { setShowClosed(false); setSessionId(s.id); setView('sessions'); setNewOpen(false); void refresh(); }}/>}
    {handoff && <HandoffEditor key={handoff.id} handoff={handoff} close={() => setHandoff(undefined)}/>}

    {history && <Modal title="轨迹上传" wide close={() => setHistory(undefined)}><div className="modal-body"><p className="muted">上传本工作台采集的对话、工具事件及来源，保存到项目的 trajectories/账号/ 目录。与成果提交分开，不包含厂商隐藏推理，不代表训练授权。</p><label className="check-row"><input type="checkbox" disabled={!state.sessions.find(s => s.id === history.id)?.binding} checked={!!state.sessions.find(s => s.id === history.id)?.autoUpload} onChange={e => void run(() => api.call('session.autoUpload', { id: history.id, enabled: e.target.checked }))}/>此会话每轮结束后自动上传（默认关闭）</label><div className="history-preview"><Markdown text={history.text}/></div></div><footer><button className="primary" disabled={!state.sessions.find(s => s.id === history.id)?.binding} onClick={() => void run(async () => { await api.call('session.uploadTrajectory', { id: history.id }); setHistory(undefined); setView('transfers'); })}><Upload size={15}/>确认上传轨迹</button></footer></Modal>}
  </div>;
}
type Run = <T>(fn: () => Promise<T>) => Promise<T | undefined>;
function ConnectModal({ settings, connection, close, run, onConnected }: { settings: Settings; connection: Snapshot['connection']; close: () => void; run: Run; onConnected: () => void }) {
  const empty: ConnectionProfile = { id: crypto.randomUUID(), name: '团队共享空间', host: '', port: 22, username: '', fingerprint: '', manifestPath: '', projects: [], workPath: '' };
  const [profile, setProfile] = useState(connection?.profile || settings.connections[0] || empty);
  const [localPath, setLocalPath] = useState(settings.localWorkspace || ''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [projectsText, setProjectsText] = useState(JSON.stringify(profile.projects, null, 2));
  const local = profile.mode === 'local';
  const select = (p: ConnectionProfile) => { setProfile(p); setProjectsText(JSON.stringify(p.projects, null, 2)); setPassword(''); setError(''); };
  const update = (key: keyof ConnectionProfile, value: unknown) => setProfile({ ...profile, [key]: value, ...(['host', 'port', 'localRoot'].includes(key) ? { fingerprint: '' } : {}) });
  const choose = (setter: (value: string) => void) => void run(async () => { const dir = await api.call<string>('choose.directory'); if (dir) setter(dir); });
  return <Modal title="连接与工作路径" close={close} wide><div className="modal-body">
    {error && <div className="inline-error" role="alert">{error}</div>}
    <label className="field">共享区类型<select aria-label="共享区类型" value={local ? 'local' : 'sftp'} onChange={e => select({ ...empty, mode: e.target.value as 'local' | 'sftp', host: e.target.value === 'local' ? 'local' : '', name: e.target.value === 'local' ? '本地联调' : '团队共享空间' })}><option value="sftp">Linux / SFTP</option><option value="local">本地文件系统（模拟权限）</option></select></label>
    <div className="callout"><Server size={19}/><div>{local ? '本地联调 · 模拟权限' : '使用管理员分配的 Linux 账号密码。'}<small>{local ? '文件真实保存在本地共享目录。权限由工作台测试桩检查，不能替代系统权限。请先在管理员版初始化目录、创建项目组和成员。' : '密码仅用于本次连接，不写入配置文件或传给 Agent。'}</small></div></div>
    <div className="row gap-bottom"><select aria-label="已保存的服务器" value={profile.id} onChange={e => { const p = settings.connections.find(x => x.id === e.target.value); if (p) select(p); }}><option value={profile.id}>{profile.name}</option>{settings.connections.filter(p => p.id !== profile.id).map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="secondary" onClick={() => select(empty)}>新增</button><button className="secondary" onClick={() => void run(async () => { const p = await api.call<ConnectionProfile | null>('profile.import'); if (p) select(p); })}>导入管理员配置</button></div>
    <div className="form-grid">
      <label className="field full">本机工作路径（必填）<div className="row"><input aria-label="本机工作路径" value={localPath} onChange={e => setLocalPath(e.target.value)}/><button className="secondary" onClick={() => choose(setLocalPath)}>选择目录</button></div></label>
      {local && <label className="field full">本地共享区根目录<div className="row"><input aria-label="本地共享区根目录" value={profile.localRoot || ''} onChange={e => update('localRoot', e.target.value)}/><button className="secondary" onClick={() => choose(value => update('localRoot', value))}>选择共享目录</button></div><small>与管理员版选择同一目录；不是本机代码工作目录。</small></label>}
      <label className="field full">{local ? '共享工作路径' : 'Linux 工作路径'}（必填）<input aria-label={local ? '共享工作路径' : 'Linux 工作路径'} value={profile.workPath || ''} placeholder="例如 /projects/workbench" onChange={e => update('workPath', e.target.value)}/><small>{local ? '相对于共享区根目录的逻辑路径，例如 /projects/workbench。连接时按模拟账号检查访问权。' : '使用 SFTP 中看到的路径；连接时实际验证目录访问权限。'}</small></label>
      <label className="field">连接名称<input value={profile.name} onChange={e => update('name', e.target.value)}/></label>
      {!local && <><label className="field">服务器地址<input value={profile.host} onChange={e => update('host', e.target.value)}/></label><label className="field">SFTP 端口<input type="number" value={profile.port} onChange={e => update('port', Number(e.target.value))}/></label></>}
      <label className="field">{'成员账号'}<input aria-label={'成员账号'} placeholder="管理员分配的姓名或工号" value={profile.username} onChange={e => update('username', e.target.value)}/></label>
      <label className="field full">登录密码<input type="password" autoComplete="off" value={password} onChange={e => setPassword(e.target.value)}/></label>
      {!local && <><label className="field full">管理员提供的服务器指纹<input value={profile.fingerprint} onChange={e => update('fingerprint', e.target.value)}/></label><label className="field full">远端项目入口清单（可选）<input value={profile.manifestPath} onChange={e => update('manifestPath', e.target.value)}/></label></>}
    </div>
    {!local && <details><summary>手动配置项目入口</summary><p className="muted small">包含 id、name、remoteRoot、uploadPath、historyPath，路径使用 SFTP 中看到的绝对路径。</p><textarea className="editor config-editor" value={projectsText} onChange={e => setProjectsText(e.target.value)}/></details>}
  </div><footer>{connection?.connected && <button className="secondary" onClick={() => void run(async () => { await api.call('remote.disconnect'); close(); })}><Unplug size={14}/>断开连接</button>}<span className="spacer"/><button className="secondary" onClick={close}>取消</button><button className="primary" disabled={busy || !profile.host || !profile.username || !password || !localPath.trim() || !profile.workPath?.trim() || (local && !profile.localRoot?.trim())} onClick={async () => { setBusy(true); setError(''); try { await api.call('remote.connect', { profile: { ...profile, projects: local ? [] : JSON.parse(projectsText) }, password, localPath }); setPassword(''); onConnected(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}>{busy ? '正在连接并验证…' : '连接并验证工作路径'}</button></footer></Modal>;
}

function CreateProjectModal({ workspace, close, created }: { workspace: string; close: () => void; created: (project: Project) => Promise<void> }) {
  const [name, setName] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <Modal title="创建远端项目" close={close}><div className="modal-body">{error && <div className="inline-error" role="alert">{error}</div>}<p className="muted">由当前项目子管理员创建，访问权限按所选共享区模式验证。</p><label className="field">项目名称<input aria-label="项目名称" placeholder="例如 实体抽取" value={name} onChange={e => setName(e.target.value)}/></label><div className="callout"><FolderOpen size={20}/><div>创建位置<small>{workspace}/{name.trim() || '项目名称'}</small><small>自动建立 trajectories 轨迹目录和 submissions 成果目录。</small></div></div><p className="muted small">轨迹上传时自动保存到 trajectories/账号/，与成果分开。同名目录不会覆盖。</p></div><footer><button className="secondary" disabled={busy} onClick={close}>取消</button><button className="primary" disabled={busy || !name.trim()} onClick={async () => { setBusy(true); setError(''); try { const project = await api.call<Project>('project.create', { name }); await created(project); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}>{busy ? '正在创建…' : '创建项目'}</button></footer></Modal>;
}
function SettingsModal({ settings, providers, auth, close, run }: { settings: Settings; providers: Snapshot['providers']; auth: Snapshot['auth']; close: () => void; run: Run }) {
  const [paths, setPaths] = useState(settings.providerPaths), [busy, setBusy] = useState(false);
  return <Modal title="CLI 与本地设置" close={close} wide><div className="modal-body"><p className="muted">工作台通过本地 CLI 运行，保留各自的个人登录。留空时自动寻找系统安装或随包提供的 CLI。</p>{(['codex', 'cursor'] as Provider[]).map(provider => { const info = providers.find(x => x.provider === provider); return <div className="provider-setting" key={provider}><div className="row"><span className={'provider-icon ' + provider}>{provider === 'codex' ? 'G' : 'C'}</span><strong>{providerLabel(provider)}</strong><span className="spacer"/><span className={'badge ' + (info?.available ? 'done' : 'error')}>{info?.available ? '已检测到 CLI' : '未找到 CLI'}</span></div><label className="field">CLI 程序路径<div className="row"><input placeholder="留空自动检测" value={paths[provider]} onChange={e => setPaths({ ...paths, [provider]: e.target.value })}/><button className="secondary" onClick={() => void run(async () => { const file = await api.call<string>('choose.executable'); if (file) setPaths({ ...paths, [provider]: file }); })}>选择</button></div></label><p className="muted small break">{info?.available ? info.path + '\n' + info.version : info?.detail}</p><ProviderAuthPanel provider={provider} auth={auth[provider]} cwd={settings.localWorkspace} stale={paths[provider] !== settings.providerPaths[provider]} beforeAction={async () => { await api.call('settings.save', { ...settings, providerPaths: paths }); }}/><div className="row"><button className="text-button" onClick={() => void api.call('open.link', provider === 'codex' ? 'https://developers.openai.com/codex/cli' : 'https://cursor.com/docs/cli/installation')}>官方安装说明</button></div></div>; })}<div className="callout"><HardDrive size={18}/><div>本机数据独立保存<small>服务器配置、会话记录、成果草稿位于 Windows 用户数据目录，不进入安装包。</small></div><button className="secondary compact" onClick={() => void api.call('open.data')}>打开目录</button></div></div><footer><button className="primary" disabled={busy} onClick={() => void run(async () => { setBusy(true); try { await api.call('settings.save', { ...settings, providerPaths: paths }); await api.call('providers.detect'); await Promise.all((['codex', 'cursor'] as Provider[]).map(provider => api.call('provider.auth', { provider, cwd: settings.localWorkspace }))); } finally { setBusy(false); } })}>{busy ? '检测中…' : '保存并检测 CLI'}</button></footer></Modal>;
}
function NewSessionModal({ settings, auth, projects, projectId, close, run, created }: { settings: Settings; auth: Snapshot['auth']; projects: Project[]; projectId: string; close: () => void; run: Run; created: (s: AgentSession) => void }) {
  const [selected, setSelected] = useState<Provider>('codex'), [cwd, setCwd] = useState(settings.lastWorkspace || settings.localWorkspace || ''), [project, setProject] = useState(projectId), [busy, setBusy] = useState(false), [model, setModel] = useState('');
  useEffect(() => setModel(''), [selected, cwd]);
  return <Modal title="新建工作会话" close={close} wide><div className="modal-body">
    <div className="provider-picker">{(['codex', 'cursor'] as Provider[]).map(p => <button aria-label={providerLabel(p)} className={selected === p ? 'selected' : ''} key={p} onClick={() => setSelected(p)}><span className={'provider-icon ' + p}>{p === 'codex' ? 'G' : 'C'}</span>{providerLabel(p)}{selected === p && <Check size={15}/>}</button>)}</div>
    <div className="new-session-grid"><div>
      <ProviderAuthPanel key={selected} provider={selected} auth={auth[selected]} cwd={cwd}/>
      <label className="field">本地工作目录<div className="row"><input aria-label="本地工作目录" placeholder="选择代码或资料所在目录" value={cwd} onChange={e => setCwd(e.target.value)}/><button className="secondary" title="选择本地工作目录" onClick={() => void run(async () => { const dir = await api.call<string>('choose.directory'); if (dir) setCwd(dir); })}><FolderOpen size={17}/></button></div></label>
      <label className="field">绑定远端项目<select value={project} onChange={e => setProject(e.target.value)}><option value="">仅本地工作</option>{projects.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
      <p className="muted small">会话建立后固定使用所选模型、工作目录和远端项目。切换左侧项目不会改变已有会话的上传目标。</p>
    </div><ModelPicker key={selected + cwd} provider={selected} cwd={cwd} ready={!!canUseProvider(auth[selected]) && auth[selected].cwd === cwd} model={model} changed={setModel}/></div>
  </div><footer><button className="secondary" onClick={close}>取消</button><button className="primary" disabled={!cwd || busy || !canUseProvider(auth[selected]) || auth[selected].cwd !== cwd} onClick={() => void run(async () => { setBusy(true); try { const s = await api.call<AgentSession>('session.create', { provider: selected, cwd, model: model || undefined, projectId: project || undefined }); created(s); } finally { setBusy(false); } })}>创建会话</button></footer></Modal>;
}
function HandoffEditor({ handoff, close }: { handoff: { id: string; text: string }; close: () => void }) {
  const key = useRef('handoff:' + handoff.id + ':' + crypto.randomUUID());
  const editor = useAutosave(key.current, handoff.text, text => api.call('handoff.save', { id: handoff.id, text }));
  const [error, setError] = useState('');
  const finish = async () => { try { await editor.flush(); close(); } catch (e: any) { setError('文件尚未保存，窗口已保留：' + e.message); } };
  return <Modal title="本地交接文件" wide close={() => void finish()}><div className="modal-body"><p className="muted">每个会话有独立的交接文件。编辑自动保存，关闭前等待保存完成。</p>{error && <div role="alert" className="inline-error">{error}</div>}<textarea className="editor handoff-editor" aria-label="交接文件正文" value={editor.value} onChange={e => editor.change(e.target.value)}/><p role="status">{editor.status}</p>{editor.status.startsWith('保存失败') && <button className="secondary" onClick={editor.retry}>重试保存</button>}</div><footer><button className="primary" onClick={() => void finish()}>保存交接文件</button></footer></Modal>;
}
createRoot(document.getElementById('root')!).render(<App/>);
