import React, { useEffect, useState } from 'react';
import type { Project, ProjectBriefState, WorkspaceAccess } from '../shared/types';
import { briefFields, type ProjectBrief } from '../shared/project-brief';
const blank = () => Object.fromEntries(briefFields.map(f => [f.key, ''])) as ProjectBrief;
export function ProjectBriefEditor({ project, groups, initialGroup, admin, close, saved }: { project?: Project; groups: WorkspaceAccess[]; initialGroup?: string; admin: boolean; close: () => void; saved: (project?: Project) => Promise<void> }) {
  const [name, setName] = useState(project?.name || ''), [group, setGroup] = useState(initialGroup || groups[0]?.groupName || '');
  const [brief, setBrief] = useState<ProjectBrief>(blank), [revision, setRevision] = useState(0), [skip, setSkip] = useState(false);
  const [busy, setBusy] = useState(!!project), [error, setError] = useState('');
  useEffect(() => { if (!project) return; let active = true; void window.workbench.call<ProjectBriefState>('project.brief', { projectId: project.id }).then(data => { if (active) { setBrief(data.brief || blank()); setRevision(data.revision); } }, e => { if (active) setError(e.message); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [project?.id]);
  return <div className="modal-backdrop"><section className="modal wide" role="dialog" aria-label="项目资料"><header><h2>{project ? '项目资料 · ' + project.name : '创建项目'}</h2><button className="secondary compact" disabled={busy} onClick={close}>关闭</button></header><div className="modal-body">
    {error && <div className="inline-error" role="alert">{error}</div>}
    {!project && <><label className="field">所属工作组<select aria-label="所属工作组" value={group} onChange={e => setGroup(e.target.value)}>{groups.map(g => <option value={g.groupName} key={g.groupName}>{g.groupLabel || g.groupName}</option>)}</select></label><label className="field">项目名称<input aria-label="项目名称" value={name} onChange={e => setName(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={skip} onChange={e => setSkip(e.target.checked)}/>先创建目录，稍后完善项目资料</label></>}
    <p className="muted small">{project ? `资料版本：${revision ? 'v' + revision : '待完善'}。` : ''}{admin ? '修改会生成新版本；成员会收到更新提示，自行选择何时采用。' : '由本组子管理员维护。可在会话中引用当前版本。'}</p>
    {!skip && briefFields.map(f => <label className="field" key={f.key}>{f.label}{f.required ? ' *' : '（可选）'}<textarea aria-label={f.label} rows={f.required ? 3 : 2} maxLength={6000} disabled={busy} readOnly={!admin} value={brief[f.key]} placeholder={f.placeholder} onChange={e => { const value = e.target.value; setBrief(previous => ({ ...previous, [f.key]: value })); }}/></label>)}
  </div><footer><button className="secondary" disabled={busy} onClick={close}>取消</button>{admin && <button className="primary" disabled={busy || !name.trim() || (!skip && briefFields.filter(f => f.required).some(f => !brief[f.key].trim()))} onClick={async () => { setBusy(true); setError(''); try { if (project) { await window.workbench.call('project.brief.save', { projectId: project.id, brief, revision }); await saved(); } else { const result = await window.workbench.call<Project>('project.create', { name, groupName: group, brief: skip ? undefined : brief }); await saved(result); } } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}>{busy ? '保存中…' : project ? '保存新版本' : '创建项目'}</button>}</footer></section></div>;
}
