import React, { useEffect, useState } from 'react';
import type { AgentSession, ProjectConclusion } from '../shared/types';
import { attachedConclusion, conclusionTitle } from '../shared/conclusion-context';

export function SessionMaterials({ session, changed }: { session: AgentSession; changed: () => Promise<void> }) {
  const [open, setOpen] = useState(false), [items, setItems] = useState<ProjectConclusion[]>([]), [selected, setSelected] = useState<string[]>([]), [query, setQuery] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { if (open) { setError(''); setSelected([]); void window.workbench.call<ProjectConclusion[]>('conclusion.list', { projectId: session.binding?.project.id }).then(setItems).catch(error => setError(error.message)); } }, [open, session.id]);
  const visible = items.filter(item => `${item.title} ${item.content}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <><button className="text-button" disabled={!session.binding} onClick={() => setOpen(true)}>添加项目资料</button>{open && <div className="modal-backdrop"><section className="modal wide" role="dialog" aria-modal="true" aria-label="添加项目资料"><header><h2>添加项目资料</h2><button className="icon" disabled={busy} aria-label="关闭资料选择" onClick={() => setOpen(false)}>×</button></header><div className="modal-body"><input aria-label="查找项目资料" placeholder="按标题或内容查找" value={query} onChange={event => setQuery(event.target.value)}/>{error && <p className="inline-error">{error}</p>}{visible.map(item => { const used = !!attachedConclusion(session, item.id); return <label className="conclusion-match-option" key={item.id}><input type="checkbox" checked={used || selected.includes(item.id)} disabled={used || busy} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))}/><span><b>{conclusionTitle(item)}{used ? ' · 已加入' : ''}</b><p>{item.content.slice(0, 180)}</p></span></label>; })}{!visible.length && <p className="muted">暂无匹配资料，可先在“项目资料”中手工新建或整理会话成果。</p>}</div><footer><button className="secondary" disabled={busy} onClick={() => setOpen(false)}>取消</button><button className="primary" disabled={busy || !selected.length} onClick={async () => { setBusy(true); setError(''); try { for (const conclusionId of selected) await window.workbench.call('session.attachConclusion', { id: session.id, conclusionId }); await changed(); setOpen(false); } catch (error: any) { setError(error.message); await changed(); } finally { setBusy(false); } }}>加入当前会话（{selected.length}）</button></footer></section></div>}</>;
}
