import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { AgentSession, SourceFile, SubsessionReport, SubsessionReportPreview } from '../shared/types';

const api = window.workbench;

export function ForkSubsessionDialog({ parent, close, created }: { parent: AgentSession; close: () => void; created: (child: AgentSession) => void }) {
  const [focus, setFocus] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="fork-subsession-title"><header><h2 id="fork-subsession-title">创建 Subsession <span className="beta-inline-tag">Beta</span></h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={close}>×</button></header><div className="modal-body"><p>从“{parent.title}”当前已保存的对话和阶段摘要派生，创建独立的工作目录与模型会话。父子会话之后的内容不会自动同步。</p><label className="field">这条探索要做什么<input autoFocus maxLength={120} value={focus} onChange={event => setFocus(event.target.value)} placeholder="例如：尝试另一种误差分析方法"/></label><p className="muted small">沿用 {parent.provider === 'codex' ? 'Codex' : parent.provider === 'claude' ? 'Claude Code' : 'Cursor'} 的模型和权限设置；探索方向会预填在子会话输入框中，创建后仍由你决定何时发送。</p>{error && <div className="inline-error" role="alert">{error}</div>}</div><footer><button className="secondary" disabled={busy} onClick={close}>取消</button><button className="primary" disabled={busy || !focus.trim()} onClick={() => void (async () => { setBusy(true); setError(''); try { created(await api.call<AgentSession>('subsession.create', { parentId: parent.id, focus })); } catch (error: any) { setError(error.message); } finally { setBusy(false); } })()}>{busy ? '正在创建独立工作区…' : '创建 Subsession'}</button></footer></section></div>;
}

export function SubsessionReportDialog({ child, close, reported }: { child: AgentSession; close: () => void; reported: () => Promise<void> }) {
  const [preview, setPreview] = useState<SubsessionReportPreview>(), [body, setBody] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = async () => { setBusy(true); setError(''); try { const value = await api.call<SubsessionReportPreview>('subsession.report.preview', { id: child.id }); setPreview(value); setBody(value.body); } catch (error: any) { setError(error.message); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, [child.id]);
  return <div className="modal-backdrop"><section className="modal wide" role="dialog" aria-modal="true" aria-labelledby="subsession-report-title"><header><h2 id="subsession-report-title">回报父会话 · {child.title}</h2><button className="icon" aria-label="关闭窗口" disabled={busy} onClick={close}>×</button></header><div className="modal-body"><p>这份回报会保存为固定版本，先出现在父会话的待查看区；不会自动发给父会话的模型或上传团队。</p>{preview && <><p className="muted small">将保存为 v{preview.nextVersion} · 截至本子会话第 {preview.messageCount} 条消息</p><label className="field">回报内容<textarea aria-label="子会话回报内容" rows={13} maxLength={128 * 1024} value={body} onChange={event => setBody(event.target.value)}/></label><details><summary>最近一轮回复与文件状态</summary><div className="subsession-report-evidence"><b>最近一轮回复</b><pre>{preview.latestReply || '尚无模型回复'}</pre><b>当前工作区文件状态</b><pre>{preview.changedFiles.length ? preview.changedFiles.join('\n') : '未检测到 Git 文件变化'}</pre></div></details></>}{error && <div className="inline-error" role="alert">{error}</div>}</div><footer><button className="secondary" disabled={busy} onClick={close}>取消</button><button className="secondary" disabled={busy} onClick={() => void load()}>刷新快照</button><button className="primary" disabled={busy || !preview || !body.trim()} onClick={() => void (async () => { setBusy(true); setError(''); try { await api.call('subsession.report.publish', { id: child.id, sourceHash: preview!.sourceHash, body }); await reported(); close(); } catch (error: any) { setError(error.message); } finally { setBusy(false); } })()}>{busy ? '正在保存…' : '回报父会话'}</button></footer></section></div>;
}

export function SubsessionPanel({ parent, children, enabled, openChild, attached, followup, changed }: { parent: AgentSession; children: AgentSession[]; enabled: boolean; openChild: (child: AgentSession) => void; attached: (sources: SourceFile[], compare: boolean) => void; followup: (child: AgentSession, report: SubsessionReport, text: string) => void; changed: () => Promise<void> }) {
  const [selected, setSelected] = useState<{ childId: string; reportId: string }>(), [followupItem, setFollowupItem] = useState<{ child: AgentSession; report: SubsessionReport }>(), [followupText, setFollowupText] = useState(''), [compareIds, setCompareIds] = useState<string[]>([]), [comparing, setComparing] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const reports = children.map(child => ({ child, report: child.reports?.at(-1) })).filter((entry): entry is { child: AgentSession; report: SubsessionReport } => !!entry.report);
  const unread = reports.filter(item => !item.report.reviewedAt).length;
  const selectedItem = selected && children.flatMap(child => (child.reports || []).map(report => ({ child, report }))).find(item => item.child.id === selected.childId && item.report.id === selected.reportId);
  const compareItems = reports.filter(item => compareIds.includes(item.child.id));
  const markRead = async (child: AgentSession, report: SubsessionReport) => { await api.call('subsession.report.review', { parentId: parent.id, childId: child.id, reportId: report.id }); await changed(); };
  const attach = async (entries: { child: AgentSession; report: SubsessionReport }[], compare: boolean) => {
    setBusy(true); setError('');
    try {
      const sources: SourceFile[] = [];
      for (const entry of entries) sources.push(await api.call<SourceFile>('subsession.report.attach', { parentId: parent.id, childId: entry.child.id, reportId: entry.report.id }));
      for (const entry of entries) await markRead(entry.child, entry.report);
      attached(sources, compare); setSelected(undefined); setComparing(false);
    } catch (error: any) { setError(error.message); }
    finally { setBusy(false); }
  };
  return <><details className="subsession-panel"><summary>Subsession · {children.length} 个探索{unread > 0 && <span className="materials-update">{unread} 条新回报</span>}</summary><div className="subsession-panel-body"><p className="muted small">子会话继续独立工作。回报先由你查看；选入父会话后，下次发送消息时模型才会读到固定版本。</p>{children.map(child => { const report = child.reports?.at(-1); const changedSinceReport = !!report && child.messages.length > report.messageCount; return <div className="subsession-card" key={child.id}><div><b>{child.title}</b><small>{child.closedAt ? '已关闭' : child.status === 'running' ? '探索中' : '可继续'} · {report ? `最新回报 v${report.version}${report.reviewedAt ? '' : ' · 待查看'}${changedSinceReport ? ' · 回报后有新进展' : ''}` : '尚无回报'}</small></div><div className="row"><button className="secondary compact" onClick={() => openChild(child)}>打开子会话</button>{report && <button className="secondary compact" onClick={() => void (async () => { setSelected({ childId: child.id, reportId: report.id }); await markRead(child, report).catch((error: Error) => setError(error.message)); })()}>查看回报</button>}{report && <label className="check-row"><input type="checkbox" aria-label={`比较回报：${child.title}`} checked={compareIds.includes(child.id)} onChange={event => setCompareIds(current => event.target.checked ? [...current, child.id] : current.filter(id => id !== child.id))}/>比较</label>}</div></div>; })}<div className="row"><button className="secondary compact" disabled={compareItems.length < 2} onClick={() => setComparing(true)}>并排比较（{compareItems.length}）</button></div>{error && <div className="inline-error" role="alert">{error}</div>}</div></details>
    {selectedItem && <div className="modal-backdrop"><section className="modal wide" role="dialog" aria-modal="true" aria-labelledby="subsession-report-detail"><header><h2 id="subsession-report-detail">{selectedItem.child.title} · 回报 v{selectedItem.report.version}</h2><button className="icon" aria-label="关闭窗口" onClick={() => setSelected(undefined)}>×</button></header><div className="modal-body"><label className="field">回报版本<select aria-label="子会话回报版本" value={selectedItem.report.id} onChange={event => setSelected({ childId: selectedItem.child.id, reportId: event.target.value })}>{selectedItem.child.reports?.map(report => <option key={report.id} value={report.id}>v{report.version} · {new Date(report.createdAt).toLocaleString('zh-CN')}</option>)}</select></label><p className="muted small">保存于 {new Date(selectedItem.report.createdAt).toLocaleString('zh-CN')} · 子会话第 {selectedItem.report.messageCount} 条消息</p><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{selectedItem.report.body}</ReactMarkdown></div><details><summary>最近回复及文件状态</summary><pre>{selectedItem.report.latestReply || '尚无模型回复'}</pre><pre>{selectedItem.report.changedFiles.join('\n') || '未检测到 Git 文件变化'}</pre></details>{error && <div className="inline-error" role="alert">{error}</div>}</div><footer><button className="secondary" onClick={() => setSelected(undefined)}>暂不处理</button><button className="secondary" disabled={!enabled || !!selectedItem.child.closedAt} onClick={() => { setFollowupItem(selectedItem); setFollowupText(''); setSelected(undefined); }}>要求补充</button><button className="primary" disabled={!enabled || busy || !!parent.closedAt} title={!enabled ? '请先开启 Beta 功能' : ''} onClick={() => void attach([selectedItem], false)}>{busy ? '正在加入…' : '加入父会话待发送内容'}</button></footer></section></div>}
    {followupItem && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="subsession-followup-title"><header><h2 id="subsession-followup-title">要求“{followupItem.child.title}”补充</h2><button className="icon" aria-label="关闭窗口" onClick={() => setFollowupItem(undefined)}>×</button></header><div className="modal-body"><p>补充要求会填入子会话输入框，仍由你检查并发送。</p><label className="field">需要补充什么<textarea autoFocus aria-label="给子会话的补充要求" rows={5} value={followupText} onChange={event => setFollowupText(event.target.value)} placeholder="例如：补测同一数据集上的运行时间，并说明验证条件。"/></label></div><footer><button className="secondary" onClick={() => setFollowupItem(undefined)}>取消</button><button className="primary" disabled={!followupText.trim()} onClick={() => { followup(followupItem.child, followupItem.report, followupText.trim()); setFollowupItem(undefined); }}>转到子会话</button></footer></section></div>}
    {comparing && <div className="modal-backdrop"><section className="modal wide" role="dialog" aria-modal="true" aria-labelledby="subsession-compare-title"><header><h2 id="subsession-compare-title">比较子会话回报</h2><button className="icon" aria-label="关闭窗口" onClick={() => setComparing(false)}>×</button></header><div className="modal-body"><div className="subsession-compare">{compareItems.map(item => <section key={item.report.id}><h3>{item.child.title} · v{item.report.version}</h3><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.report.body}</ReactMarkdown></div><details><summary>最近回复与文件状态</summary><pre>{item.report.latestReply}</pre><pre>{item.report.changedFiles.join('\n')}</pre></details></section>)}</div>{error && <div className="inline-error" role="alert">{error}</div>}</div><footer><button className="secondary" onClick={() => setComparing(false)}>关闭</button><button className="primary" disabled={!enabled || busy || !!parent.closedAt} title={!enabled ? '请先开启 Beta 功能' : ''} onClick={() => void attach(compareItems, true)}>{busy ? '正在加入…' : '加入父会话，准备让 Agent 比较'}</button></footer></section></div>}
  </>;
}
